/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:icons

DO NOT EDIT THIS FILE DIRECTLY
*/

import type { ComponentProps } from "react";

export const Add = (props: ComponentProps<"svg">) => {
  return (
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}>
      <path
        d="M22 12.7501H14.0205L12.7501 14.0205V22H11.2499V14.0205L9.97948 12.7501H2V11.2499H9.97948L11.2499 9.97948V2H12.7501V9.97948L14.0205 11.2499H22V12.7501Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
