/**
 * THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:
 *
 * `yarn generate:icons`
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 */

import type { ComponentProps } from "react";

export const AIAgent = (props: ComponentProps<"svg">) => {
  return (
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}>
      <path d="M10 17H8V11H10V17Z" fill="currentColor"></path>
      <path d="M16 17H14V11H16V17Z" fill="currentColor"></path>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M12.5 3V7H18L21 10V18L18 21H6L3 18V10L6 7H11.5V4H9.5V3H12.5ZM4 10.4141V17.5859L6.41406 20H17.5859L20 17.5859V10.4141L17.5859 8H6.41406L4 10.4141Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
