/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:icons

DO NOT EDIT THIS FILE DIRECTLY
*/

import type { ComponentProps } from "react";

export const ArrowLeft = (props: ComponentProps<"svg">) => {
  return (
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}>
      <path
        d="M11.3242 4.05859L4.49512 10.8984V11.2363H21V12.7637H4.49512V13.1016L11.3242 19.9414L10.2676 21L3 13.7217V10.2783L10.2676 3L11.3242 4.05859Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
