/**
 * THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:
 *
 * `yarn generate:icons`
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 */

import type { ComponentProps } from "react";

export const ArrowDown = (props: ComponentProps<"svg">) => {
  return (
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}>
      <path
        d="M4.05859 12.6758L10.8984 19.5049L11.2363 19.5049L11.2363 3L12.7637 3L12.7637 19.5049L13.1016 19.5049L19.9414 12.6758L21 13.7324L13.7217 21L10.2783 21L3 13.7324L4.05859 12.6758Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
