/**
 * THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:
 *
 * `yarn generate:icons`
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 */

import type { ComponentProps } from "react";

export const CaretRight = (props: ComponentProps<"svg">) => {
  return (
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}>
      <path
        d="M8 19.9414L14.8291 13.1016L14.8291 10.8984L8 4.05859L9.05664 3L16.3242 10.2783L16.3242 13.7217L9.05664 21L8 19.9414Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
