/**
 * THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:
 *
 * `yarn generate:icons`
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 */

import type { ComponentProps } from "react";

export const Error = (props: ComponentProps<"svg">) => {
  return (
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}>
      <path
        d="M13.0423 15.7576V16.7879L12.526 17.303H11.4932L10.9769 16.7879V15.7576L11.4932 15.2424H12.526L13.0423 15.7576Z"
        fill="currentColor"
      ></path>
      <path
        d="M13.3005 7.51515L12.7841 13.697L12.2678 14.2121H11.7514L11.2351 13.697L10.7187 7.51515L11.2351 7H12.7841L13.3005 7.51515Z"
        fill="currentColor"
      ></path>
      <path
        d="M21 8V16L16 21H8L3 16V8L8 3H16L21 8ZM4 8.41406V15.5859L8.41406 20H15.5859L20 15.5859V8.41406L15.5859 4H8.41406L4 8.41406Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
