/**
 * THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:
 *
 * `yarn generate:icons`
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 */

import type { ComponentProps } from "react";

export const Icon_social_microsoft = (props: ComponentProps<"svg">) => {
  return (
    <svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" {...props}>
      <path
        d="M9.59812 9.59812H1.8877V1.8877H9.59812V9.59812Z"
        fill="currentColor"
      ></path>
      <path
        d="M18.1117 9.59812H10.4014V1.8877H18.1117V9.59812Z"
        fill="currentColor"
      ></path>
      <path
        d="M9.59793 18.1118H1.8877V10.4014H9.59793V18.1118Z"
        fill="currentColor"
      ></path>
      <path
        d="M18.1117 18.1118H10.4014V10.4014H18.1117V18.1118Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
