/**
 * THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:
 *
 * `yarn generate:icons`
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 */

import type { ComponentProps } from "react";

export const Info = (props: ComponentProps<"svg">) => {
  return (
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}>
      <path
        d="M18.1582 3L21 5.8418V18.1582L18.1582 21H5.8418L3 18.1582V5.8418L5.8418 3H18.1582ZM4 6.25586V17.7441L6.25586 20H17.7441L20 17.7441V6.25586L17.7441 4H6.25586L4 6.25586Z"
        fill="currentColor"
      ></path>
      <path
        d="M10.9875 16.5562V10.4812L11.4937 9.975H12.5062L13.0125 10.4812V16.5562L12.5062 17.0625H11.4937L10.9875 16.5562Z"
        fill="currentColor"
      ></path>
      <path
        d="M10.9875 8.45625V7.44375L11.4937 6.9375H12.5062L13.0125 7.44375V8.45625L12.5062 8.9625H11.4937L10.9875 8.45625Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
