/**
 * THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:
 *
 * `yarn generate:icons`
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 */

import { Add } from "./Add";
import { AIAgentSolid } from "./AIAgentSolid";
import { AIAgent } from "./AIAgent";
import { AIData } from "./AIData";
import { AIModel } from "./AIModel";
import { AITask } from "./AITask";
import { AIVideoGen } from "./AIVideoGen";
import { AI } from "./AI";
import { ArrowDown } from "./ArrowDown";
import { ArrowLeft } from "./ArrowLeft";
import { ArrowRight } from "./ArrowRight";
import { ArrowUpLeft } from "./ArrowUpLeft";
import { ArrowUpRight } from "./ArrowUpRight";
import { ArrowUp } from "./ArrowUp";
import { Auto } from "./Auto";
import { Blackhole } from "./Blackhole";
import { Board } from "./Board";
import { CaretDown } from "./CaretDown";
import { CaretLeft } from "./CaretLeft";
import { CaretRight } from "./CaretRight";
import { CaretUp } from "./CaretUp";
import { Cart } from "./Cart";
import { ChatSolid } from "./ChatSolid";
import { Chat } from "./Chat";
import { Checkmark } from "./Checkmark";
import { Chip } from "./Chip";
import { CircleXSolid } from "./CircleXSolid";
import { CircleX } from "./CircleX";
import { Close } from "./Close";
import { CloudServerSolid } from "./CloudServerSolid";
import { CloudServer } from "./CloudServer";
import { Copy } from "./Copy";
import { DocumentSolid } from "./DocumentSolid";
import { Document } from "./Document";
import { Download } from "./Download";
import { ErrorSolid } from "./ErrorSolid";
import { Error } from "./Error";
import { Folder } from "./Folder";
import { GalaxyRack } from "./GalaxyRack";
import { Galaxy } from "./Galaxy";
import { Globe } from "./Globe";
import { InfoSolid } from "./InfoSolid";
import { Info } from "./Info";
import { Link } from "./Link";
import { Location } from "./Location";
import { LoudBox } from "./LoudBox";
import { Menu } from "./Menu";
import { Minus } from "./Minus";
import { ModeDark } from "./ModeDark";
import { ModeLight } from "./ModeLight";
import { ModeSystem } from "./ModeSystem";
import { ModelDeepSeekColor } from "./ModelDeepSeekColor";
import { ModelDeepSeek } from "./ModelDeepSeek";
import { ModelFalconColor } from "./ModelFalconColor";
import { ModelFalcon } from "./ModelFalcon";
import { ModelGoogleColor } from "./ModelGoogleColor";
import { ModelGoogle } from "./ModelGoogle";
import { ModelLlamaColor } from "./ModelLlamaColor";
import { ModelLlama } from "./ModelLlama";
import { ModelOpenAI } from "./ModelOpenAI";
import { ModelQwenColor } from "./ModelQwenColor";
import { ModelQwen } from "./ModelQwen";
import { Monitor } from "./Monitor";
import { OrgDeveloper } from "./OrgDeveloper";
import { OrgExperience } from "./OrgExperience";
import { OrgOperations } from "./OrgOperations";
import { OrgSystems } from "./OrgSystems";
import { OrgUniversity } from "./OrgUniversity";
import { Phone } from "./Phone";
import { Quasar } from "./Quasar";
import { QuietBox } from "./QuietBox";
import { Reset } from "./Reset";
import { Search } from "./Search";
import { ServerSolid } from "./ServerSolid";
import { Server } from "./Server";
import { ShieldSolid } from "./ShieldSolid";
import { Shield } from "./Shield";
import { Size } from "./Size";
import { SocialApple } from "./SocialApple";
import { SocialDiscord } from "./SocialDiscord";
import { SocialFacebook } from "./SocialFacebook";
import { SocialGitHub } from "./SocialGitHub";
import { SocialGoogle } from "./SocialGoogle";
import { SocialLinkedIn } from "./SocialLinkedIn";
import { SocialMicrosoft } from "./SocialMicrosoft";
import { SocialX } from "./SocialX";
import { SocialYouTube } from "./SocialYouTube";
import { SuccessSolid } from "./SuccessSolid";
import { Success } from "./Success";
import { Tensix } from "./Tensix";
import { Tenstorrent } from "./Tenstorrent";
import { TrashSolid } from "./TrashSolid";
import { Trash } from "./Trash";
import { TTForgeFE } from "./TTForgeFE";
import { TTForge } from "./TTForge";
import { TTLLK } from "./TTLLK";
import { TTMetalium } from "./TTMetalium";
import { TTNn } from "./TTNn";
import { TTTorch } from "./TTTorch";
import { TTXLA } from "./TTXLA";
import { Upload } from "./Upload";
import { UserMultipleSolid } from "./UserMultipleSolid";
import { UserMultiple } from "./UserMultiple";
import { UserSolid } from "./UserSolid";
import { User } from "./User";
import { WarningSolid } from "./WarningSolid";
import { Warning } from "./Warning";
import { Wormhole } from "./Wormhole";

export const registry = {
  add: Add,
  "ai-agent-solid": AIAgentSolid,
  "ai-agent": AIAgent,
  "ai-data": AIData,
  "ai-model": AIModel,
  "ai-task": AITask,
  "ai-video-gen": AIVideoGen,
  ai: AI,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-left": ArrowUpLeft,
  "arrow-up-right": ArrowUpRight,
  "arrow-up": ArrowUp,
  auto: Auto,
  blackhole: Blackhole,
  board: Board,
  "caret-down": CaretDown,
  "caret-left": CaretLeft,
  "caret-right": CaretRight,
  "caret-up": CaretUp,
  cart: Cart,
  "chat-solid": ChatSolid,
  chat: Chat,
  checkmark: Checkmark,
  chip: Chip,
  "circle-x-solid": CircleXSolid,
  "circle-x": CircleX,
  close: Close,
  "cloud-server-solid": CloudServerSolid,
  "cloud-server": CloudServer,
  copy: Copy,
  "document-solid": DocumentSolid,
  document: Document,
  download: Download,
  "error-solid": ErrorSolid,
  error: Error,
  folder: Folder,
  "galaxy-rack": GalaxyRack,
  galaxy: Galaxy,
  globe: Globe,
  "info-solid": InfoSolid,
  info: Info,
  link: Link,
  location: Location,
  loudbox: LoudBox,
  menu: Menu,
  minus: Minus,
  "mode-dark": ModeDark,
  "mode-light": ModeLight,
  "mode-system": ModeSystem,
  "model-deepseek-color": ModelDeepSeekColor,
  "model-deepseek": ModelDeepSeek,
  "model-falcon-color": ModelFalconColor,
  "model-falcon": ModelFalcon,
  "model-google-color": ModelGoogleColor,
  "model-google": ModelGoogle,
  "model-llama-color": ModelLlamaColor,
  "model-llama": ModelLlama,
  "model-openai": ModelOpenAI,
  "model-qwen-color": ModelQwenColor,
  "model-qwen": ModelQwen,
  monitor: Monitor,
  "org-developer": OrgDeveloper,
  "org-experience": OrgExperience,
  "org-operations": OrgOperations,
  "org-systems": OrgSystems,
  "org-university": OrgUniversity,
  phone: Phone,
  quasar: Quasar,
  quietbox: QuietBox,
  reset: Reset,
  search: Search,
  "server-solid": ServerSolid,
  server: Server,
  "shield-solid": ShieldSolid,
  shield: Shield,
  size: Size,
  "social-apple": SocialApple,
  "social-discord": SocialDiscord,
  "social-facebook": SocialFacebook,
  "social-github": SocialGitHub,
  "social-google": SocialGoogle,
  "social-linkedin": SocialLinkedIn,
  "social-microsoft": SocialMicrosoft,
  "social-x": SocialX,
  "social-youtube": SocialYouTube,
  "success-solid": SuccessSolid,
  success: Success,
  tensix: Tensix,
  tenstorrent: Tenstorrent,
  "trash-solid": TrashSolid,
  trash: Trash,
  "tt-forge-fe": TTForgeFE,
  "tt-forge": TTForge,
  "tt-llk": TTLLK,
  "tt-metalium": TTMetalium,
  "tt-nn": TTNn,
  "tt-torch": TTTorch,
  "tt-xla": TTXLA,
  upload: Upload,
  "user-multiple-solid": UserMultipleSolid,
  "user-multiple": UserMultiple,
  "user-solid": UserSolid,
  user: User,
  "warning-solid": WarningSolid,
  warning: Warning,
  wormhole: Wormhole,
};
