/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:icons

DO NOT EDIT THIS FILE DIRECTLY
*/

import { Add } from "./Add.js";
import { AIAgentSolid } from "./AIAgentSolid.js";
import { AIAgent } from "./AIAgent.js";
import { AIData } from "./AIData.js";
import { AIModel } from "./AIModel.js";
import { AITask } from "./AITask.js";
import { AIVideoGen } from "./AIVideoGen.js";
import { AI } from "./AI.js";
import { ArrowDown } from "./ArrowDown.js";
import { ArrowLeft } from "./ArrowLeft.js";
import { ArrowRight } from "./ArrowRight.js";
import { ArrowUpLeft } from "./ArrowUpLeft.js";
import { ArrowUpRight } from "./ArrowUpRight.js";
import { ArrowUp } from "./ArrowUp.js";
import { Auto } from "./Auto.js";
import { Blackhole } from "./Blackhole.js";
import { Board } from "./Board.js";
import { CaretDown } from "./CaretDown.js";
import { CaretLeft } from "./CaretLeft.js";
import { CaretRight } from "./CaretRight.js";
import { CaretUp } from "./CaretUp.js";
import { Cart } from "./Cart.js";
import { ChatSolid } from "./ChatSolid.js";
import { Chat } from "./Chat.js";
import { Checkmark } from "./Checkmark.js";
import { Chip } from "./Chip.js";
import { CircleXSolid } from "./CircleXSolid.js";
import { CircleX } from "./CircleX.js";
import { Close } from "./Close.js";
import { CloudServerSolid } from "./CloudServerSolid.js";
import { CloudServer } from "./CloudServer.js";
import { Copy } from "./Copy.js";
import { DocumentSolid } from "./DocumentSolid.js";
import { Document } from "./Document.js";
import { Download } from "./Download.js";
import { ErrorSolid } from "./ErrorSolid.js";
import { Error } from "./Error.js";
import { Folder } from "./Folder.js";
import { GalaxyRack } from "./GalaxyRack.js";
import { Galaxy } from "./Galaxy.js";
import { Globe } from "./Globe.js";
import { InfoSolid } from "./InfoSolid.js";
import { Info } from "./Info.js";
import { Link } from "./Link.js";
import { Location } from "./Location.js";
import { LoudBox } from "./LoudBox.js";
import { Menu } from "./Menu.js";
import { Minus } from "./Minus.js";
import { ModeDark } from "./ModeDark.js";
import { ModeLight } from "./ModeLight.js";
import { ModeSystem } from "./ModeSystem.js";
import { ModelDeepSeekColor } from "./ModelDeepSeekColor.js";
import { ModelDeepSeek } from "./ModelDeepSeek.js";
import { ModelFalconColor } from "./ModelFalconColor.js";
import { ModelFalcon } from "./ModelFalcon.js";
import { ModelGoogleColor } from "./ModelGoogleColor.js";
import { ModelGoogle } from "./ModelGoogle.js";
import { ModelLlamaColor } from "./ModelLlamaColor.js";
import { ModelLlama } from "./ModelLlama.js";
import { ModelOpenAI } from "./ModelOpenAI.js";
import { ModelQwenColor } from "./ModelQwenColor.js";
import { ModelQwen } from "./ModelQwen.js";
import { Monitor } from "./Monitor.js";
import { OrgDeveloper } from "./OrgDeveloper.js";
import { OrgExperience } from "./OrgExperience.js";
import { OrgOperations } from "./OrgOperations.js";
import { OrgSystems } from "./OrgSystems.js";
import { OrgUniversity } from "./OrgUniversity.js";
import { Phone } from "./Phone.js";
import { Quasar } from "./Quasar.js";
import { QuietBox } from "./QuietBox.js";
import { Reset } from "./Reset.js";
import { Search } from "./Search.js";
import { ServerSolid } from "./ServerSolid.js";
import { Server } from "./Server.js";
import { ShieldSolid } from "./ShieldSolid.js";
import { Shield } from "./Shield.js";
import { Size } from "./Size.js";
import { SocialApple } from "./SocialApple.js";
import { SocialDiscord } from "./SocialDiscord.js";
import { SocialFacebook } from "./SocialFacebook.js";
import { SocialGitHub } from "./SocialGitHub.js";
import { SocialGoogle } from "./SocialGoogle.js";
import { SocialLinkedIn } from "./SocialLinkedIn.js";
import { SocialMicrosoft } from "./SocialMicrosoft.js";
import { SocialX } from "./SocialX.js";
import { SocialYouTube } from "./SocialYouTube.js";
import { SuccessSolid } from "./SuccessSolid.js";
import { Success } from "./Success.js";
import { Tensix } from "./Tensix.js";
import { Tenstorrent } from "./Tenstorrent.js";
import { TrashSolid } from "./TrashSolid.js";
import { Trash } from "./Trash.js";
import { TTForgeFE } from "./TTForgeFE.js";
import { TTForge } from "./TTForge.js";
import { TTLLK } from "./TTLLK.js";
import { TTMetalium } from "./TTMetalium.js";
import { TTNN } from "./TTNN.js";
import { TTTorch } from "./TTTorch.js";
import { TTXLA } from "./TTXLA.js";
import { Upload } from "./Upload.js";
import { UserMultipleSolid } from "./UserMultipleSolid.js";
import { UserMultiple } from "./UserMultiple.js";
import { UserSolid } from "./UserSolid.js";
import { User } from "./User.js";
import { WarningSolid } from "./WarningSolid.js";
import { Warning } from "./Warning.js";
import { Wormhole } from "./Wormhole.js";

export const registry = {
  add: Add,
  "ai-agent-solid": AIAgentSolid,
  "ai-agent": AIAgent,
  "ai-data": AIData,
  "ai-model": AIModel,
  "ai-task": AITask,
  "ai-video-gen": AIVideoGen,
  ai: AI,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-left": ArrowUpLeft,
  "arrow-up-right": ArrowUpRight,
  "arrow-up": ArrowUp,
  auto: Auto,
  blackhole: Blackhole,
  board: Board,
  "caret-down": CaretDown,
  "caret-left": CaretLeft,
  "caret-right": CaretRight,
  "caret-up": CaretUp,
  cart: Cart,
  "chat-solid": ChatSolid,
  chat: Chat,
  checkmark: Checkmark,
  chip: Chip,
  "circle-x-solid": CircleXSolid,
  "circle-x": CircleX,
  close: Close,
  "cloud-server-solid": CloudServerSolid,
  "cloud-server": CloudServer,
  copy: Copy,
  "document-solid": DocumentSolid,
  document: Document,
  download: Download,
  "error-solid": ErrorSolid,
  error: Error,
  folder: Folder,
  "galaxy-rack": GalaxyRack,
  galaxy: Galaxy,
  globe: Globe,
  "info-solid": InfoSolid,
  info: Info,
  link: Link,
  location: Location,
  loudbox: LoudBox,
  menu: Menu,
  minus: Minus,
  "mode-dark": ModeDark,
  "mode-light": ModeLight,
  "mode-system": ModeSystem,
  "model-deepseek-color": ModelDeepSeekColor,
  "model-deepseek": ModelDeepSeek,
  "model-falcon-color": ModelFalconColor,
  "model-falcon": ModelFalcon,
  "model-google-color": ModelGoogleColor,
  "model-google": ModelGoogle,
  "model-llama-color": ModelLlamaColor,
  "model-llama": ModelLlama,
  "model-openai": ModelOpenAI,
  "model-qwen-color": ModelQwenColor,
  "model-qwen": ModelQwen,
  monitor: Monitor,
  "org-developer": OrgDeveloper,
  "org-experience": OrgExperience,
  "org-operations": OrgOperations,
  "org-systems": OrgSystems,
  "org-university": OrgUniversity,
  phone: Phone,
  quasar: Quasar,
  quietbox: QuietBox,
  reset: Reset,
  search: Search,
  "server-solid": ServerSolid,
  server: Server,
  "shield-solid": ShieldSolid,
  shield: Shield,
  size: Size,
  "social-apple": SocialApple,
  "social-discord": SocialDiscord,
  "social-facebook": SocialFacebook,
  "social-github": SocialGitHub,
  "social-google": SocialGoogle,
  "social-linkedin": SocialLinkedIn,
  "social-microsoft": SocialMicrosoft,
  "social-x": SocialX,
  "social-youtube": SocialYouTube,
  "success-solid": SuccessSolid,
  success: Success,
  tensix: Tensix,
  tenstorrent: Tenstorrent,
  "trash-solid": TrashSolid,
  trash: Trash,
  "tt-forge-fe": TTForgeFE,
  "tt-forge": TTForge,
  "tt-llk": TTLLK,
  "tt-metalium": TTMetalium,
  "tt-nn": TTNN,
  "tt-torch": TTTorch,
  "tt-xla": TTXLA,
  upload: Upload,
  "user-multiple-solid": UserMultipleSolid,
  "user-multiple": UserMultiple,
  "user-solid": UserSolid,
  user: User,
  "warning-solid": WarningSolid,
  warning: Warning,
  wormhole: Wormhole,
};
