/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:icons

DO NOT EDIT THIS FILE DIRECTLY
*/

import type { ComponentProps } from "react";

export const Reset = (props: ComponentProps<"svg">) => {
  return (
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}>
      <path
        d="M21 8.49316V16.0068L15.874 21.25H8.12598L3 16.0068V13.1211H4.5V15.3955L8.75684 19.75H15.2422L19.5 15.3955V9.10449L15.2422 4.75H8.76855L5.17871 8.625H10.625V10.125H4.27246L3 8.85254V2.5H4.5V7.14941L8.11328 3.25H15.874L21 8.49316Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
