/**
 * THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:
 *
 * `yarn generate:icons`
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 */

import type { ComponentProps } from "react";

export const UserSolid = (props: ComponentProps<"svg">) => {
  return (
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}>
      <path d="M20 18V21H4V18L7.07129 15H17L20 18Z" fill="currentColor"></path>
      <path
        d="M16.75 5.5V10.5L14.75 13H9.25L7.25 10.5V5.5L9.25 3H14.75L16.75 5.5Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
