; https://docs.vale.sh/topics/.vale.ini

StylesPath = .vale

MinAlertLevel = suggestion

Packages = ai-tells, \
  https://github.com/tbhb/vale-ai-tells/releases/download/v1.37.0/ai-tells-commits.zip

# markdown
[{apps,packages,docs}/*.{md,mdx}]
BasedOnStyles = Vale, ai-tells

# code comments
[{apps,packages}/*.{ts,tsx,css}]
BasedOnStyles = ai-tells
