# https://docs.vale.sh/topics/.vale.ini

# where our vale styles (rules) are downloaded from after running
# `vale sync` (done in `yarn lint:prose`)
StylesPath = .vale

MinAlertLevel = suggestion

Packages = ai-tells
  # https://github.com/tbhb/vale-ai-tells

[formats]
mdx = md
mjs = js
mts = ts

# all files
[*]
# don't check for spelling (errors on all kinds of problems because of
# component names and jsdoc comments)
Vale.Spelling = NO

# docs
[{apps,packages,docs}/*.{md,mdx}]
BasedOnStyles = Vale, ai-tells

# code comments
[{apps,packages}/*.{js,mjs,mts,ts,tsx,css}]
BasedOnStyles = ai-tells

# don't flag CSS variables
[*.css]
ai-tells.DoubleHyphen = NO

# ignore
[{**/.next/**,apps/website/public/**,packages/vesper/CHANGELOG.md}]
BasedOnStyles =
