/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:leading

DO NOT EDIT THIS FILE DIRECTLY
*/

export const leading = {
  none: "100%",
  tight: "110%",
  snug: "120%",
  normal: "140%",
  relaxed: "150%",
  loose: "175%",
};
