/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:radius

DO NOT EDIT THIS FILE DIRECTLY
*/

export const radius = {
  "1": "4px",
  "2": "8px",
  "3": "12px",
  "4": "16px",
  "6": "24px",
  "7": "28px",
  half: "2px",
};
