import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import { optimize } from "svgo";
import { unified } from "unified";
import rehypeParse from "rehype-parse";
import rehypeStringify from "rehype-stringify";
import { visit } from "unist-util-visit";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const AUTO_GENERATED_WARNING = `/**
 * THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:
 *
 * \`yarn generate:icons\`
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 */`;

// transform an svg file name into its id, ie. user-multiple.svg -> user-multiple
const getIconId = (fileName: string) => fileName.slice(0, -4);

// transform an icon id into its component name, ie. user-multiple -> Icon_user_multiple
const getComponentName = (iconId: string) =>
  "Icon_" + iconId.split("-").join("_");

const iconFiles = fs
  .readdirSync(path.resolve(__dirname, "../assets/icons"))
  .filter((file) => file.endsWith(".svg"));

if (iconFiles.length === 0) {
  throw new Error("No SVG files found in assets/icons directory");
}

const icons = iconFiles.map((fileName) => {
  // get the icon svg as utf-8
  const raw = fs.readFileSync(
    path.resolve(__dirname, "../assets/icons", fileName),
    "utf-8",
  );

  const id = getIconId(fileName);
  const name = getComponentName(id);

  // prefix ids using the icon id to prevent collisions between elements inside other svgs
  const { data } = optimize(raw, {
    plugins: [{ name: "prefixIds", params: { prefix: name } }],
  });

  // convert the optimized icon svg to a tree
  const tree = unified().use(rehypeParse, { fragment: true }).parse(data);

  // traverse and patch the tree
  visit(tree, "element", (node, _, parent) => {
    // convert the root <svg> element into a <symbol> element and remove extraneous properties
    if (node.tagName === "svg" && parent?.type === "root") {
      delete node.properties.width;
      delete node.properties.height;
      delete node.properties.fill;
      return;
    }

    const shouldPatchValue = (value: unknown) =>
      typeof value === "string" &&
      value !== "none" &&
      value !== "currentColor" &&
      !value.startsWith("url(");

    // patch non-colored icons so their fills and strokes use currentColor
    if (!name.includes("color")) {
      if ("fill" in node.properties && shouldPatchValue(node.properties.fill)) {
        node.properties.fill = "currentColor";
      }
      if (
        "stroke" in node.properties &&
        shouldPatchValue(node.properties.stroke)
      ) {
        node.properties.stroke = "currentColor";
      }
    }
  });

  // serialize tree into a string again now that it's been optimized and patched
  const markdown = unified().use(rehypeStringify).stringify(tree);

  return { id, name, markdown };
});

// remove existing files in Icon component folder
fs.rmSync(path.resolve(__dirname, "../src/components/Icon"), {
  recursive: true,
  force: true,
});

// recreate Icon component folder
fs.mkdirSync(path.resolve(__dirname, "../src/components/Icon"), {
  recursive: true,
});

// create an individual component file for each icon
icons.forEach((icon) => {
  // spread {...props} into the opening svg tag
  const markdown = icon.markdown.replace(/<svg([^>]*)>/s, "<svg$1 {...props}>");

  const fileContents = `
${AUTO_GENERATED_WARNING}

import type { ComponentProps } from 'react';

export const ${icon.name} = (props: ComponentProps<'svg'>) => {
  return ${markdown}
}
`;

  fs.writeFileSync(
    path.resolve(__dirname, `../src/components/Icon/${icon.name}.tsx`),
    fileContents,
  );
});

// import individual component files into icon registry
fs.writeFileSync(
  path.resolve(__dirname, `../src/components/Icon/registry.ts`),
  `
${AUTO_GENERATED_WARNING}

${icons.map((icon) => `import { ${icon.name} } from './${icon.name}'`).join("\n")}

export const registry = {
  ${icons.map((icon) => `"${icon.id}": ${icon.name},`).join("\n")}
}
`,
);

// create master component that imports icons from registry (this is tree-shakeable)
fs.writeFileSync(
  path.resolve(__dirname, `../src/components/Icon/Icon.tsx`),
  `
  ${AUTO_GENERATED_WARNING}

  import type { ComponentProps } from "react";
  import { registry } from "./registry";

  export type IconKind = keyof typeof registry

  export interface IconProps extends ComponentProps<"svg"> {
    kind: IconKind;
  }

  export function Icon({ kind, ...props }: IconProps) {
    const Component = registry[kind]
    if (!Component) return null

    return (
      <Component {...props} />
    );
  }`,
);

// export master icon component from barrel file
fs.writeFileSync(
  path.resolve(__dirname, `../src/components/Icon/index.ts`),
  `${AUTO_GENERATED_WARNING}

  export * from './Icon'`,
);
