export type DesignToken<T> = {
  $value: T;
};

export type DesignTokenTree<T> =
  | DesignToken<T>
  | { [key: string]: DesignToken<T> };

const isDesignToken = <T>(value: DesignTokenTree<T>): value is DesignToken<T> =>
  "$value" in value;

export const parseDesignTokenTree = <T>({
  tree,
  processToken,
  acceptToken = () => true,
}: {
  tree: DesignTokenTree<T>;
  processToken: (
    name: string,
    token: DesignToken<T>,
  ) => [name: string, value: string];
  acceptToken?: (tokenName: string) => boolean;
}) => {
  const tokens: [name: string, value: string][] = [];

  const createTokens = (tree: DesignTokenTree<T>, tokenName = "") => {
    if (isDesignToken(tree)) {
      tokens.push(processToken(tokenName, tree));
      return;
    }

    Object.entries(tree).forEach(([tokenPart, tree]) => {
      if (tokenPart.startsWith("$")) return;
      createTokens(tree, tokenName ? `${tokenName}-${tokenPart}` : tokenPart);
    });
  };
  createTokens(tree);

  return Object.fromEntries(tokens.filter((entry) => acceptToken(entry[0])));
};

export const getGeneratedCodeWarning = (command: string) => `/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

${command}

DO NOT EDIT THIS FILE DIRECTLY
*/`;
