import * as nodePath from "node:path";

export const getGeneratedCodeWarning = (command: string) => `/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

${command}

DO NOT EDIT THIS FILE DIRECTLY
*/`;

/**
 * the root directory of package vesper
 */
export const packageDir = nodePath.resolve(import.meta.dirname, "./..");

/**
 * path relative to package/vesper
 *
 * - must start with `./` (relative to package root)
 * - must not escape the package root (e.g. `../`)
 *
 * @example
 * ```ts
 * const yay: PackagePath = "./src";   // ✅
 * const bad: PackagePath = "../src";   // ❌
 * const sad: PackagePath = "./../src"; // ❌
 * ```
 */
export type PackagePath<T extends string> = T extends `./${infer Rest}`
  ? Rest extends `.${string}`
    ? never
    : T
  : never;

/**
 * resolves a file or directory path relative to package/vesper
 *
 * can be used with `fs` methods that require a file path
 *
 * for safety, paths can't escape the package root
 *
 * @example
 * ```ts
 * const filePath = resolvePackagePath("./src/index.ts");
 * fs.readFileSync(filePath);
 * ```
 */
export const resolvePackagePath = <T extends string>(
  /** the file or directory path to resolve - **must start with `./`** (relative to package root), and may not escape the package root */
  path: PackagePath<T>,
): string => {
  // for safety, don't allow paths that escape the package root
  if (path.startsWith("..") || path.startsWith("./..")) {
    throw new Error("filePath may not escape the package root");
  }
  if (!path.startsWith("./")) {
    throw new Error("filePath must start with ./ (relative to package root)");
  }

  return nodePath.resolve(packageDir, path);
};
