/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:icons

DO NOT EDIT THIS FILE DIRECTLY
*/

import type { ComponentProps } from "react";

export const ArrowUpLeft = (props: ComponentProps<"svg">) => {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M16 4.5293H6.12109L5.86426 4.78516L21 19.9209L19.9209 21L4.78516 5.86426L4.5293 6.12109V16H3V5.4873L5.4873 3H16V4.5293Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
