/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:icons

DO NOT EDIT THIS FILE DIRECTLY
*/

import type { ComponentProps } from "react";

export const ArrowUp = (props: ComponentProps<"svg">) => {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M19.9414 11.3242L13.1016 4.49512L12.7637 4.49512L12.7637 21L11.2363 21L11.2363 4.49512L10.8984 4.49512L4.05859 11.3242L3 10.2676L10.2783 3L13.7217 3L21 10.2676L19.9414 11.3242Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
