/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:icons

DO NOT EDIT THIS FILE DIRECTLY
*/

import type { ComponentProps } from "react";

export const Bolt = (props: ComponentProps<"svg">) => {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M13.1667 10.8889L17.8333 2L5 9.77778L10.8333 13.1111L6.16667 22L19 14.2222L13.1667 10.8889Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
