/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:icons

DO NOT EDIT THIS FILE DIRECTLY
*/

import type { ComponentProps } from "react";

export const Checkmark = (props: ComponentProps<"svg">) => {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M22 6.07124L8.46804 18.9532H6.67287L2 14.5048L3.17444 13.3868L7.36066 17.3719H7.78025L20.8256 4.95322L22 6.07124Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
