/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:icons

DO NOT EDIT THIS FILE DIRECTLY
*/

import type { ComponentProps } from "react";

export const ClosePanel = (props: ComponentProps<"svg">) => {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path d="M4.5 20H3V4H4.5V20Z" fill="currentColor"></path>
      <path
        d="M13.6514 5.82324L8.28809 11.1943V11.2812H21V12.7188H8.28809V12.8047L13.6514 18.1768L12.6523 19.1768L6.875 13.3916V10.6094L12.6523 4.82324L13.6514 5.82324Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
