/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:icons

DO NOT EDIT THIS FILE DIRECTLY
*/

import type { ComponentProps } from "react";
import type { IconKind } from "./types";
import { registry } from "./registry";

export interface IconProps extends ComponentProps<"svg"> {
  kind: IconKind;
}

export function Icon({ kind, ...props }: IconProps) {
  const Component = registry[kind];
  if (!Component) return null;

  return <Component {...props} />;
}
