/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:icons

DO NOT EDIT THIS FILE DIRECTLY
*/

import type { ComponentProps } from "react";

export const List = (props: ComponentProps<"svg">) => {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path d="M5 20H3V18H5V20Z" fill="currentColor"></path>
      <path d="M21 19.75H7V18.25H21V19.75Z" fill="currentColor"></path>
      <path d="M5 12.5H3V10.5H5V12.5Z" fill="currentColor"></path>
      <path d="M21 12.25H7V10.75H21V12.25Z" fill="currentColor"></path>
      <path d="M5 6H3V4H5V6Z" fill="currentColor"></path>
      <path d="M21 5.75H7V4.25H21V5.75Z" fill="currentColor"></path>
    </svg>
  );
};
