/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:icons

DO NOT EDIT THIS FILE DIRECTLY
*/

import type { ComponentProps } from "react";

export const OrgOperations = (props: ComponentProps<"svg">) => {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M7.70592 5.87521C5.93588 5.87521 3.91555 5.70864 4.00269 8.42945H6.79424L6.23542 20.8824L10.706 16.4118L12.9413 22L15.1766 16.4118L19.6472 20.8824L18.5295 4.67647L16.853 3C16.853 3 10.4266 3 9.02953 3C7.63249 3 7.35306 4.67647 7.35306 4.67647L7.1883 5.8733L7.70592 5.87521ZM13.5001 5.23529H9.02953C9.02953 7.47058 13.5001 7.47058 13.5001 5.23529Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
