/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:icons

DO NOT EDIT THIS FILE DIRECTLY
*/

import type { ComponentProps } from "react";

export const OrgSystems = (props: ComponentProps<"svg">) => {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M14.5 6.50012L15.5 7.50012V14.006L14.5 15.006H10V16.5001H12.5V17.5001H5V16.5001H7.5V15.0001L3 15.006L2 14.006V7.50012L3 6.50012H14.5ZM3 7.50012V14.006H14.5V7.50012H3Z"
        fill="currentColor"
      ></path>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M22 7.50012V17.5001H21L19.5 16.0001H19L17.5 17.5001H16.5V7.50012L17.5 6.50012H21L22 7.50012ZM18.5 13.5001V15.006L20 15.0001V13.5001H18.5ZM17.5 11.0001H21V10.006L17.5 10.0001V11.0001ZM17.5 9.00012H21V8.00012H17.5V9.00012Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
