/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:icons

DO NOT EDIT THIS FILE DIRECTLY
*/

import type { ComponentProps, ComponentType } from "react";

import { Add } from "./add";
import { AI } from "./ai";
import { AIAgent } from "./ai-agent";
import { AIAgentSolid } from "./ai-agent-solid";
import { AIData } from "./ai-data";
import { AIModel } from "./ai-model";
import { AITask } from "./ai-task";
import { AIVideoGen } from "./ai-video-gen";
import { ArrowDown } from "./arrow-down";
import { ArrowLeft } from "./arrow-left";
import { ArrowRight } from "./arrow-right";
import { ArrowUp } from "./arrow-up";
import { ArrowUpLeft } from "./arrow-up-left";
import { ArrowUpRight } from "./arrow-up-right";
import { Auto } from "./auto";
import { Blackhole } from "./blackhole";
import { Board } from "./board";
import { Bolt } from "./bolt";
import { Bug } from "./bug";
import { CaretDown } from "./caret-down";
import { CaretLeft } from "./caret-left";
import { CaretRight } from "./caret-right";
import { CaretUp } from "./caret-up";
import { Cart } from "./cart";
import { Chat } from "./chat";
import { ChatSolid } from "./chat-solid";
import { Checkmark } from "./checkmark";
import { Chip } from "./chip";
import { CircleAdd } from "./circle-add";
import { CircleAddSolid } from "./circle-add-solid";
import { CircleX } from "./circle-x";
import { CircleXSolid } from "./circle-x-solid";
import { Clock } from "./clock";
import { ClockCountdown } from "./clock-countdown";
import { ClockCounterClockwise } from "./clock-counter-clockwise";
import { Close } from "./close";
import { ClosePanel } from "./close-panel";
import { CloudServer } from "./cloud-server";
import { CloudServerSolid } from "./cloud-server-solid";
import { Copy } from "./copy";
import { Document } from "./document";
import { DocumentSolid } from "./document-solid";
import { Download } from "./download";
import { Ellipses } from "./ellipses";
import { Error } from "./error";
import { ErrorSolid } from "./error-solid";
import { Eye } from "./eye";
import { EyeSlash } from "./eye-slash";
import { Folder } from "./folder";
import { Galaxy } from "./galaxy";
import { GalaxyRack } from "./galaxy-rack";
import { Gear } from "./gear";
import { GearSolid } from "./gear-solid";
import { Globe } from "./globe";
import { Grid } from "./grid";
import { Info } from "./info";
import { InfoSolid } from "./info-solid";
import { Link } from "./link";
import { List } from "./list";
import { Location } from "./location";
import { Lock } from "./lock";
import { LockFill } from "./lock-fill";
import { LoudBox } from "./loudbox";
import { Menu } from "./menu";
import { Microphone } from "./microphone";
import { Minus } from "./minus";
import { ModeDark } from "./mode-dark";
import { ModeLight } from "./mode-light";
import { ModeSystem } from "./mode-system";
import { ModelDeepSeek } from "./model-deepseek";
import { ModelDeepSeekColor } from "./model-deepseek-color";
import { ModelFalcon } from "./model-falcon";
import { ModelFalconColor } from "./model-falcon-color";
import { ModelGoogle } from "./model-google";
import { ModelGoogleColor } from "./model-google-color";
import { ModelLlama } from "./model-llama";
import { ModelLlamaColor } from "./model-llama-color";
import { ModelOpenAI } from "./model-openai";
import { ModelQwen } from "./model-qwen";
import { ModelQwenColor } from "./model-qwen-color";
import { Monitor } from "./monitor";
import { OpenPanel } from "./open-panel";
import { OrgDeveloper } from "./org-developer";
import { OrgExperience } from "./org-experience";
import { OrgOperations } from "./org-operations";
import { OrgSystems } from "./org-systems";
import { OrgUniversity } from "./org-university";
import { Phone } from "./phone";
import { Quasar } from "./quasar";
import { QuietBox } from "./quietbox";
import { Reset } from "./reset";
import { Search } from "./search";
import { Server } from "./server";
import { ServerSolid } from "./server-solid";
import { Shield } from "./shield";
import { ShieldSolid } from "./shield-solid";
import { Sidebar } from "./sidebar";
import { Size } from "./size";
import { SocialDiscord } from "./social-discord";
import { SocialFacebook } from "./social-facebook";
import { SocialGitHub } from "./social-github";
import { SocialLinkedIn } from "./social-linkedin";
import { SocialX } from "./social-x";
import { SocialYouTube } from "./social-youtube";
import { Spinner } from "./spinner";
import { Success } from "./success";
import { SuccessSolid } from "./success-solid";
import { Tensix } from "./tensix";
import { Tenstorrent } from "./tenstorrent";
import { Trash } from "./trash";
import { TrashSolid } from "./trash-solid";
import { TTForge } from "./tt-forge";
import { TTForgeFE } from "./tt-forge-fe";
import { TTLang } from "./tt-lang";
import { TTLLK } from "./tt-llk";
import { TTMetalium } from "./tt-metalium";
import { TTNN } from "./tt-nn";
import { TTTorch } from "./tt-torch";
import { TTXLA } from "./tt-xla";
import type { IconKind } from "./types";
import { Upload } from "./upload";
import { User } from "./user";
import { UserMultiple } from "./user-multiple";
import { UserMultipleSolid } from "./user-multiple-solid";
import { UserSolid } from "./user-solid";
import { Warning } from "./warning";
import { WarningSolid } from "./warning-solid";
import { Wormhole } from "./wormhole";

export const registry: {
  [K in IconKind]: ComponentType<ComponentProps<"svg">>;
} = {
  add: Add,
  "ai-agent-solid": AIAgentSolid,
  "ai-agent": AIAgent,
  "ai-data": AIData,
  "ai-model": AIModel,
  "ai-task": AITask,
  "ai-video-gen": AIVideoGen,
  ai: AI,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-left": ArrowUpLeft,
  "arrow-up-right": ArrowUpRight,
  "arrow-up": ArrowUp,
  auto: Auto,
  blackhole: Blackhole,
  board: Board,
  bolt: Bolt,
  bug: Bug,
  "caret-down": CaretDown,
  "caret-left": CaretLeft,
  "caret-right": CaretRight,
  "caret-up": CaretUp,
  cart: Cart,
  "chat-solid": ChatSolid,
  chat: Chat,
  checkmark: Checkmark,
  chip: Chip,
  "circle-add-solid": CircleAddSolid,
  "circle-add": CircleAdd,
  "circle-x-solid": CircleXSolid,
  "circle-x": CircleX,
  "clock-countdown": ClockCountdown,
  "clock-counter-clockwise": ClockCounterClockwise,
  clock: Clock,
  "close-panel": ClosePanel,
  close: Close,
  "cloud-server-solid": CloudServerSolid,
  "cloud-server": CloudServer,
  copy: Copy,
  "document-solid": DocumentSolid,
  document: Document,
  download: Download,
  ellipses: Ellipses,
  "error-solid": ErrorSolid,
  error: Error,
  "eye-slash": EyeSlash,
  eye: Eye,
  folder: Folder,
  "galaxy-rack": GalaxyRack,
  galaxy: Galaxy,
  "gear-solid": GearSolid,
  gear: Gear,
  globe: Globe,
  grid: Grid,
  "info-solid": InfoSolid,
  info: Info,
  link: Link,
  list: List,
  location: Location,
  "lock-fill": LockFill,
  lock: Lock,
  loudbox: LoudBox,
  menu: Menu,
  microphone: Microphone,
  minus: Minus,
  "mode-dark": ModeDark,
  "mode-light": ModeLight,
  "mode-system": ModeSystem,
  "model-deepseek-color": ModelDeepSeekColor,
  "model-deepseek": ModelDeepSeek,
  "model-falcon-color": ModelFalconColor,
  "model-falcon": ModelFalcon,
  "model-google-color": ModelGoogleColor,
  "model-google": ModelGoogle,
  "model-llama-color": ModelLlamaColor,
  "model-llama": ModelLlama,
  "model-openai": ModelOpenAI,
  "model-qwen-color": ModelQwenColor,
  "model-qwen": ModelQwen,
  monitor: Monitor,
  "open-panel": OpenPanel,
  "org-developer": OrgDeveloper,
  "org-experience": OrgExperience,
  "org-operations": OrgOperations,
  "org-systems": OrgSystems,
  "org-university": OrgUniversity,
  phone: Phone,
  quasar: Quasar,
  quietbox: QuietBox,
  reset: Reset,
  search: Search,
  "server-solid": ServerSolid,
  server: Server,
  "shield-solid": ShieldSolid,
  shield: Shield,
  sidebar: Sidebar,
  size: Size,
  "social-discord": SocialDiscord,
  "social-facebook": SocialFacebook,
  "social-github": SocialGitHub,
  "social-linkedin": SocialLinkedIn,
  "social-x": SocialX,
  "social-youtube": SocialYouTube,
  spinner: Spinner,
  "success-solid": SuccessSolid,
  success: Success,
  tensix: Tensix,
  tenstorrent: Tenstorrent,
  "trash-solid": TrashSolid,
  trash: Trash,
  "tt-forge-fe": TTForgeFE,
  "tt-forge": TTForge,
  "tt-lang": TTLang,
  "tt-llk": TTLLK,
  "tt-metalium": TTMetalium,
  "tt-nn": TTNN,
  "tt-torch": TTTorch,
  "tt-xla": TTXLA,
  upload: Upload,
  "user-multiple-solid": UserMultipleSolid,
  "user-multiple": UserMultiple,
  "user-solid": UserSolid,
  user: User,
  "warning-solid": WarningSolid,
  warning: Warning,
  wormhole: Wormhole,
};
