/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:icons

DO NOT EDIT THIS FILE DIRECTLY
*/

import type { ComponentProps } from "react";

export const Tenstorrent = (props: ComponentProps<"svg">) => {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M16.8 13.3698L12 16.1151L7.20002 13.3698V18.8603L12 21.6L16.8 18.8603V13.3698Z"
        fill="currentColor"
      ></path>
      <path
        d="M16.8 7.88492L12 10.6301L7.20002 7.88492L7.20002 13.3698L2.40002 10.6301V5.14522L7.20002 2.39999L16.8 7.88492Z"
        fill="currentColor"
      ></path>
      <path
        d="M16.8 13.3698L21.6 10.6301V5.14522L16.8 2.39999L16.8 13.3698Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
