/**
 * How a form input's label is associated with its control.
 *
 * - `htmlFor` — a `<label for>` pointing at the control's `id`. Only valid for labelable elements
 *   (`input`, `select`, `textarea`, `button`, `meter`, `output`, `progress`).
 * - `aria-labelledby` — the control references the label element's `id`. Required for grouping
 *   elements such as `fieldset` and `role="radiogroup"`, which `<label for>` cannot target.
 */
export type FormControlLabelAssociation = "htmlFor" | "aria-labelledby";

export interface GetFormControlPropsOptions {
  /**
   * The `id` applied to the control element. May be undefined for components whose control id is
   * generated by a primitive and therefore unavailable on first render.
   */
  controlId?: string;
  /** The `id` applied to the message element */
  messageId: string;
  /** The `id` applied to the label element, when associating via `aria-labelledby` */
  labelId?: string;
  /** The label text, when one is displayed */
  label?: string;
  /** The message text, when one is displayed */
  message?: string;
  /** Whether the control is required, which appends an asterisk to the label */
  required?: boolean;
  /** Whether the control is in an invalid state, normally derived from `variant === "error"` */
  invalid?: boolean;
  /** The accessible name used when the consumer supplies neither `aria-label` nor `aria-labelledby` */
  defaultAriaLabel?: string;
  /** A consumer-supplied `aria-label` */
  ariaLabel?: string;
  /** A consumer-supplied `aria-labelledby` */
  ariaLabelledby?: string;
  /** A consumer-supplied `aria-describedby`, merged with the message id rather than replaced */
  ariaDescribedby?: string;
  /** A consumer-supplied `aria-invalid`, which takes precedence over `invalid` */
  ariaInvalid?: boolean | "true" | "false" | "grammar" | "spelling";
  /** How the label is associated with the control. @default htmlFor */
  labelAssociation?: FormControlLabelAssociation;
}

export interface FormControlProps {
  /** The control's `aria-describedby`, merging any consumer value with the message id */
  describedBy: string | undefined;
  /** The control's `aria-labelledby`, set only when associating via `aria-labelledby` */
  labelledBy: string | undefined;
  /** The control's accessible name, suppressed when `aria-labelledby` supplies one instead */
  ariaLabel: string | undefined;
  /** The control's `aria-invalid` */
  ariaInvalid: boolean | "true" | "false" | "grammar" | "spelling" | undefined;
  /** The `label` prop for `FormInputWrapper` */
  labelProps: { text: string; htmlFor?: string; id?: string } | undefined;
  /** The `message` prop for `FormInputWrapper` */
  messageProps: { text: string; id: string } | undefined;
}

/**
 * Builds the shared accessibility wiring every form input needs: the merged `aria-describedby`, the
 * resolved accessible name, the invalid state, and the `label` and `message` props for
 * `FormInputWrapper`.
 *
 * Three rules are worth calling out:
 *
 * - The message is always associated through `aria-describedby`, which is universally supported.
 *   `aria-errormessage` is left to the consumer: it is only meaningful when pointing at a specific
 *   error node, and it adds nothing over `aria-describedby` for the message this component renders.
 * - A supplied `aria-labelledby` suppresses the default `aria-label`, so the two don't compete for
 *   the accessible name.
 * - Consumer values always win over derived ones.
 *
 * Id generation stays with the caller for now, because deriving ids changes the generated values.
 *
 * @example
 * const { describedBy, ariaInvalid } = getFormControlProps({
 *   controlId,
 *   messageId,
 *   message,
 *   invalid: variant === "error",
 * });
 */
export function getFormControlProps({
  controlId,
  messageId,
  labelId,
  label,
  message,
  required,
  invalid,
  defaultAriaLabel,
  ariaLabel,
  ariaLabelledby,
  ariaDescribedby,
  ariaInvalid,
  labelAssociation = "htmlFor",
}: GetFormControlPropsOptions): FormControlProps {
  const usesHtmlFor = labelAssociation === "htmlFor";

  const labelledBy =
    ariaLabelledby ?? (!usesHtmlFor && label ? labelId : undefined);

  // if an additional aria-describedby is supplied, this ensures that both ids get used
  const describedBy =
    [ariaDescribedby, message ? messageId : undefined]
      .filter(Boolean)
      .join(" ") || undefined;

  const labelProps = label
    ? {
        text: required ? `${label} *` : label,
        ...(usesHtmlFor ? { htmlFor: controlId } : { id: labelId }),
      }
    : undefined;

  return {
    describedBy,
    labelledBy,
    // a supplied aria-labelledby already provides the accessible name, so the default would only
    // compete with it
    ariaLabel: ariaLabel ?? (labelledBy ? undefined : defaultAriaLabel),
    ariaInvalid: ariaInvalid ?? (invalid || undefined),
    labelProps,
    messageProps: message ? { text: message, id: messageId } : undefined,
  };
}
