/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:tailwind

DO NOT EDIT THIS FILE DIRECTLY
*/

import { extendTailwindMerge } from "tailwind-merge";
import { describe, expect, test } from "vitest";

import { withVesper } from "@/utils/tailwind-merge";

const twMerge = extendTailwindMerge(withVesper);

const tokens = {
  color: [
    "static-black",
    "static-white",
    "transparent",
    "stone-0",
    "stone-50",
    "stone-100",
    "stone-200",
    "stone-300",
    "stone-400",
    "stone-500",
    "stone-600",
    "stone-700",
    "stone-800",
    "stone-900",
    "teal-0",
    "teal-50",
    "teal-100",
    "teal-200",
    "teal-300",
    "teal-400",
    "teal-500",
    "teal-600",
    "teal-700",
    "teal-800",
    "teal-900",
    "purple-0",
    "purple-50",
    "purple-100",
    "purple-200",
    "purple-300",
    "purple-400",
    "purple-500",
    "purple-600",
    "purple-700",
    "purple-800",
    "purple-900",
    "mint-0",
    "mint-50",
    "mint-100",
    "mint-200",
    "mint-300",
    "mint-400",
    "mint-500",
    "mint-600",
    "mint-700",
    "mint-800",
    "mint-900",
    "pink-0",
    "pink-50",
    "pink-100",
    "pink-200",
    "pink-300",
    "pink-400",
    "pink-500",
    "pink-600",
    "pink-700",
    "pink-800",
    "pink-900",
    "yellow-0",
    "yellow-50",
    "yellow-100",
    "yellow-200",
    "yellow-300",
    "yellow-400",
    "yellow-500",
    "yellow-600",
    "yellow-700",
    "yellow-800",
    "yellow-900",
    "green-0",
    "green-50",
    "green-100",
    "green-200",
    "green-300",
    "green-400",
    "green-500",
    "green-600",
    "green-700",
    "green-800",
    "green-900",
    "red-0",
    "red-50",
    "red-100",
    "red-200",
    "red-300",
    "red-400",
    "red-500",
    "red-600",
    "red-700",
    "red-800",
    "red-900",
    "amber-0",
    "amber-50",
    "amber-100",
    "amber-200",
    "amber-300",
    "amber-400",
    "amber-500",
    "amber-600",
    "amber-700",
    "amber-800",
    "amber-900",
    "sky-0",
    "sky-50",
    "sky-100",
    "sky-200",
    "sky-300",
    "sky-400",
    "sky-500",
    "sky-600",
    "sky-700",
    "sky-800",
    "sky-900",
    "alpha-stone-0",
    "alpha-stone-50",
    "alpha-stone-100",
    "alpha-stone-200",
    "alpha-stone-300",
    "alpha-stone-400",
    "alpha-stone-500",
    "alpha-stone-600",
    "alpha-stone-700",
    "alpha-stone-800",
    "alpha-stone-900",
    "alpha-contrast-0",
    "alpha-contrast-50",
    "alpha-contrast-100",
    "alpha-contrast-200",
    "alpha-contrast-300",
    "alpha-contrast-400",
    "alpha-contrast-500",
    "alpha-contrast-600",
    "alpha-contrast-700",
    "alpha-contrast-800",
    "alpha-contrast-900",
    "alpha-inverse-0",
    "alpha-inverse-50",
    "alpha-inverse-100",
    "alpha-inverse-200",
    "alpha-inverse-300",
    "alpha-inverse-400",
    "alpha-inverse-500",
    "alpha-inverse-600",
    "alpha-inverse-700",
    "alpha-inverse-800",
    "alpha-inverse-900",
    "alpha-black-0",
    "alpha-black-50",
    "alpha-black-100",
    "alpha-black-200",
    "alpha-black-300",
    "alpha-black-400",
    "alpha-black-500",
    "alpha-black-600",
    "alpha-black-700",
    "alpha-black-800",
    "alpha-black-900",
    "alpha-white-0",
    "alpha-white-50",
    "alpha-white-100",
    "alpha-white-200",
    "alpha-white-300",
    "alpha-white-400",
    "alpha-white-500",
    "alpha-white-600",
    "alpha-white-700",
    "alpha-white-800",
    "alpha-white-900",
    "background-primary",
    "background-secondary",
    "background-tertiary",
    "background-disabled",
    "background-inverse-primary",
    "background-inverse-secondary",
    "background-inverse-disabled",
    "background-accent-subtle",
    "background-accent-base",
    "background-success-subtle",
    "background-success-base",
    "background-warning-subtle",
    "background-warning-base",
    "background-error-subtle",
    "background-error-base",
    "background-info-subtle",
    "background-info-base",
    "background-static-white",
    "background-static-black",
    "background-brand-purple-subtle",
    "background-brand-purple-base",
    "background-brand-mint-subtle",
    "background-brand-mint-base",
    "background-brand-pink-subtle",
    "background-brand-pink-base",
    "background-brand-yellow-subtle",
    "background-brand-yellow-base",
    "text-primary",
    "text-secondary",
    "text-tertiary",
    "text-disabled",
    "text-inverse-primary",
    "text-inverse-secondary",
    "text-inverse-tertiary",
    "text-alpha-disabled",
    "text-on-color",
    "text-accent",
    "text-success",
    "text-warning",
    "text-error",
    "text-info",
    "text-static-black",
    "text-static-white",
    "text-link-default",
    "text-link-hover",
    "text-link-visited",
    "text-link-disabled",
    "text-brand-purple",
    "text-brand-mint",
    "text-brand-pink",
    "text-brand-yellow",
    "icon-primary",
    "icon-secondary",
    "icon-tertiary",
    "icon-disabled",
    "icon-inverse-primary",
    "icon-inverse-secondary",
    "icon-inverse-tertiary",
    "icon-inverse-disabled",
    "icon-on-color",
    "icon-accent",
    "icon-success",
    "icon-warning",
    "icon-error",
    "icon-info",
    "icon-static-black",
    "icon-static-white",
    "icon-brand-purple",
    "icon-brand-mint",
    "icon-brand-pink",
    "icon-brand-yellow",
    "border-primary",
    "border-secondary",
    "border-tertiary",
    "border-strong",
    "border-disabled",
    "border-focus",
    "border-inverse-primary",
    "border-inverse-secondary",
    "border-inverse-strong",
    "border-inverse-disabled",
    "border-inverse-focus",
    "border-static-white",
    "border-static-black",
    "border-accent-subtle",
    "border-accent-base",
    "border-success-subtle",
    "border-success-base",
    "border-warning-subtle",
    "border-warning-base",
    "border-error-subtle",
    "border-error-base",
    "border-info-subtle",
    "border-info-base",
    "border-brand-purple-subtle",
    "border-brand-purple-base",
    "border-brand-mint-subtle",
    "border-brand-mint-base",
    "border-brand-pink-subtle",
    "border-brand-pink-base",
    "border-brand-yellow-subtle",
    "border-brand-yellow-base",
    "scrim-contrast-subtle",
    "scrim-contrast-base",
    "scrim-inverse-subtle",
    "scrim-inverse-base",
    "state-neutral-hover",
    "state-neutral-active",
    "state-contrast-hover",
    "state-contrast-active",
    "state-inverse-hover",
    "state-inverse-active",
    "tint-neutral-100",
    "tint-neutral-200",
    "tint-neutral-300",
    "tint-neutral-400",
    "tint-contrast-100",
    "tint-contrast-200",
    "tint-contrast-300",
    "tint-contrast-400",
    "tint-inverse-100",
    "tint-inverse-200",
    "tint-inverse-300",
    "tint-inverse-400",
  ],
  font: ["sans", "mono"],
  leading: ["none", "tight", "snug", "normal", "relaxed", "loose"],
  radius: ["1", "2", "3", "4", "6", "7", "half"],
  shadow: ["100", "200", "300", "400", "inset-100", "inset-200", "focus-ring"],
  spacing: [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "8",
    "10",
    "12",
    "14",
    "16",
    "20",
    "24",
    "28",
    "32",
    "40",
    "half",
    "micro",
  ],
  tracking: [
    "tightest",
    "tighter",
    "tight",
    "normal",
    "wide",
    "wider",
    "widest",
  ],
  "transition-duration": ["fast", "default", "slow"],
  "border-width": ["base", "strong"],
  "outline-width": ["base", "strong"],
};

/**
 * asserts that `a` and `b` are in the same class group,
 * ie. whichever class comes last wins
 */
const expectConflict = (a: string, b: string) => {
  expect(twMerge(`${a} ${b}`), `${a} ${b}`).toBe(b);
  expect(twMerge(`${b} ${a}`), `${b} ${a}`).toBe(a);
};

/**
 * asserts that `b` overrides `a` when it comes after it,
 * but that `a` does not override `b` when it comes after it
 */
const expectOverride = (a: string, b: string) => {
  expect(twMerge(`${a} ${b}`), `${a} ${b}`).toBe(b);
  expect(twMerge(`${b} ${a}`), `${b} ${a}`).toBe(`${b} ${a}`);
};

describe("withVesper", () => {
  // theme scales extended with vesper tokens
  describe("theme", () => {
    describe("color", () => {
      test.each(tokens["color"])(
        "bg-vesper-%s conflicts with bg-red-500",
        (token) => {
          expectConflict("bg-red-500", `bg-vesper-${token}`);
        },
      );

      test.each(tokens["color"])(
        "text-vesper-%s conflicts with text-red-500",
        (token) => {
          expectConflict("text-red-500", `text-vesper-${token}`);
        },
      );

      test.each(tokens["color"])(
        "border-vesper-%s conflicts with border-red-500",
        (token) => {
          expectConflict("border-red-500", `border-vesper-${token}`);
        },
      );

      test.each(tokens["color"])(
        "divide-vesper-%s conflicts with divide-red-500",
        (token) => {
          expectConflict("divide-red-500", `divide-vesper-${token}`);
        },
      );

      test.each(tokens["color"])(
        "outline-vesper-%s conflicts with outline-red-500",
        (token) => {
          expectConflict("outline-red-500", `outline-vesper-${token}`);
        },
      );

      test.each(tokens["color"])(
        "ring-vesper-%s conflicts with ring-red-500",
        (token) => {
          expectConflict("ring-red-500", `ring-vesper-${token}`);
        },
      );

      test.each(tokens["color"])(
        "fill-vesper-%s conflicts with fill-red-500",
        (token) => {
          expectConflict("fill-red-500", `fill-vesper-${token}`);
        },
      );

      test.each(tokens["color"])(
        "stroke-vesper-%s conflicts with stroke-red-500",
        (token) => {
          expectConflict("stroke-red-500", `stroke-vesper-${token}`);
        },
      );
    });

    describe("font", () => {
      test.each(tokens["font"])(
        "font-vesper-%s conflicts with font-sans",
        (token) => {
          expectConflict("font-sans", `font-vesper-${token}`);
        },
      );
    });

    describe("leading", () => {
      test.each(tokens["leading"])(
        "leading-vesper-%s conflicts with leading-6",
        (token) => {
          expectConflict("leading-6", `leading-vesper-${token}`);
        },
      );
    });

    describe("radius", () => {
      test.each(tokens["radius"])(
        "rounded-vesper-%s conflicts with rounded-md",
        (token) => {
          expectConflict("rounded-md", `rounded-vesper-${token}`);
        },
      );

      test.each(tokens["radius"])(
        "rounded-t-vesper-%s conflicts with rounded-t-md",
        (token) => {
          expectConflict("rounded-t-md", `rounded-t-vesper-${token}`);
        },
      );
    });

    describe("shadow", () => {
      test.each(tokens["shadow"])(
        "shadow-vesper-%s conflicts with shadow-lg",
        (token) => {
          expectConflict("shadow-lg", `shadow-vesper-${token}`);
        },
      );
    });

    describe("spacing", () => {
      test.each(tokens["spacing"])(
        "p-vesper-%s conflicts with p-2",
        (token) => {
          expectConflict("p-2", `p-vesper-${token}`);
        },
      );

      test.each(tokens["spacing"])(
        "m-vesper-%s conflicts with m-2",
        (token) => {
          expectConflict("m-2", `m-vesper-${token}`);
        },
      );

      test.each(tokens["spacing"])(
        "gap-vesper-%s conflicts with gap-2",
        (token) => {
          expectConflict("gap-2", `gap-vesper-${token}`);
        },
      );

      test.each(tokens["spacing"])(
        "w-vesper-%s conflicts with w-2",
        (token) => {
          expectConflict("w-2", `w-vesper-${token}`);
        },
      );

      test.each(tokens["spacing"])(
        "h-vesper-%s conflicts with h-2",
        (token) => {
          expectConflict("h-2", `h-vesper-${token}`);
        },
      );

      test.each(tokens["spacing"])(
        "inset-vesper-%s conflicts with inset-2",
        (token) => {
          expectConflict("inset-2", `inset-vesper-${token}`);
        },
      );
    });

    describe("tracking", () => {
      test.each(tokens["tracking"])(
        "tracking-vesper-%s conflicts with tracking-wide",
        (token) => {
          expectConflict("tracking-wide", `tracking-vesper-${token}`);
        },
      );
    });
  });

  // theme variable namespaces without a tailwind-merge theme scale
  describe("class groups", () => {
    describe("border-width", () => {
      test.each(tokens["border-width"])(
        "border-vesper-%s conflicts with border-2",
        (token) => {
          expectConflict("border-2", `border-vesper-${token}`);
        },
      );

      test.each(tokens["border-width"])(
        "border-x-vesper-%s conflicts with border-x-2",
        (token) => {
          expectConflict("border-x-2", `border-x-vesper-${token}`);
        },
      );

      test.each(tokens["border-width"])(
        "border-y-vesper-%s conflicts with border-y-2",
        (token) => {
          expectConflict("border-y-2", `border-y-vesper-${token}`);
        },
      );

      test.each(tokens["border-width"])(
        "border-s-vesper-%s conflicts with border-s-2",
        (token) => {
          expectConflict("border-s-2", `border-s-vesper-${token}`);
        },
      );

      test.each(tokens["border-width"])(
        "border-e-vesper-%s conflicts with border-e-2",
        (token) => {
          expectConflict("border-e-2", `border-e-vesper-${token}`);
        },
      );

      test.each(tokens["border-width"])(
        "border-bs-vesper-%s conflicts with border-bs-2",
        (token) => {
          expectConflict("border-bs-2", `border-bs-vesper-${token}`);
        },
      );

      test.each(tokens["border-width"])(
        "border-be-vesper-%s conflicts with border-be-2",
        (token) => {
          expectConflict("border-be-2", `border-be-vesper-${token}`);
        },
      );

      test.each(tokens["border-width"])(
        "border-t-vesper-%s conflicts with border-t-2",
        (token) => {
          expectConflict("border-t-2", `border-t-vesper-${token}`);
        },
      );

      test.each(tokens["border-width"])(
        "border-r-vesper-%s conflicts with border-r-2",
        (token) => {
          expectConflict("border-r-2", `border-r-vesper-${token}`);
        },
      );

      test.each(tokens["border-width"])(
        "border-b-vesper-%s conflicts with border-b-2",
        (token) => {
          expectConflict("border-b-2", `border-b-vesper-${token}`);
        },
      );

      test.each(tokens["border-width"])(
        "border-l-vesper-%s conflicts with border-l-2",
        (token) => {
          expectConflict("border-l-2", `border-l-vesper-${token}`);
        },
      );

      test.each(tokens["border-width"])(
        "divide-x-vesper-%s conflicts with divide-x-2",
        (token) => {
          expectConflict("divide-x-2", `divide-x-vesper-${token}`);
        },
      );

      test.each(tokens["border-width"])(
        "divide-y-vesper-%s conflicts with divide-y-2",
        (token) => {
          expectConflict("divide-y-2", `divide-y-vesper-${token}`);
        },
      );
    });

    describe("outline-width", () => {
      test.each(tokens["outline-width"])(
        "outline-vesper-%s conflicts with outline-2",
        (token) => {
          expectConflict("outline-2", `outline-vesper-${token}`);
        },
      );
    });

    describe("transition-duration", () => {
      test.each(tokens["transition-duration"])(
        "duration-vesper-%s conflicts with duration-150",
        (token) => {
          expectConflict("duration-150", `duration-vesper-${token}`);
        },
      );
    });
  });

  // custom utilities
  describe("custom utilities", () => {
    describe("vesper.bg-vesper-dot-pattern", () => {
      const classNames = [
        "bg-vesper-dot-pattern-primary",
        "bg-vesper-dot-pattern-secondary",
        "bg-vesper-dot-pattern-tertiary",
        ...tokens["color"].map((token) => `bg-vesper-dot-pattern-${token}`),
        "bg-vesper-dot-pattern-inverse",
        ...tokens["color"].map(
          (token) => `bg-vesper-dot-pattern-inverse-${token}`,
        ),
      ];

      const representatives = [
        "bg-vesper-dot-pattern-primary",
        "bg-vesper-dot-pattern-secondary",
        "bg-vesper-dot-pattern-tertiary",
        "bg-vesper-dot-pattern-static-black",
        "bg-vesper-dot-pattern-inverse",
        "bg-vesper-dot-pattern-inverse-static-black",
      ];

      test.each(classNames)(
        "%s overrides bg-red-500 (bg-color)",
        (className) => {
          expectOverride("bg-red-500", className);
        },
      );

      test.each(classNames)("%s overrides bg-none (bg-image)", (className) => {
        expectOverride("bg-none", className);
      });

      test.each(classNames)(
        "%s overrides bg-top (bg-position)",
        (className) => {
          expectOverride("bg-top", className);
        },
      );

      test.each(classNames)(
        "%s overrides bg-no-repeat (bg-repeat)",
        (className) => {
          expectOverride("bg-no-repeat", className);
        },
      );

      test.each(classNames)(
        "%s conflicts with other vesper.bg-vesper-dot-pattern utilities",
        (className) => {
          representatives
            .filter((representative) => representative !== className)
            .forEach((representative) => {
              expectConflict(representative, className);
            });
        },
      );
    });
  });
});
