/*
THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:tailwind-merge

DO NOT EDIT THIS FILE DIRECTLY
*/

import { extendTailwindMerge } from "tailwind-merge";
import { describe, expect, test } from "vitest";

import { withVesper } from "@/utils/tailwind-merge";

const twMerge = extendTailwindMerge(withVesper);

/** `--color-vesper-*` */
const COLOR = [
  "static-black",
  "static-white",
  "transparent",
  "stone-0",
  "stone-50",
  "stone-100",
  "stone-200",
  "stone-300",
  "stone-400",
  "stone-500",
  "stone-600",
  "stone-700",
  "stone-800",
  "stone-900",
  "teal-0",
  "teal-50",
  "teal-100",
  "teal-200",
  "teal-300",
  "teal-400",
  "teal-500",
  "teal-600",
  "teal-700",
  "teal-800",
  "teal-900",
  "purple-0",
  "purple-50",
  "purple-100",
  "purple-200",
  "purple-300",
  "purple-400",
  "purple-500",
  "purple-600",
  "purple-700",
  "purple-800",
  "purple-900",
  "mint-0",
  "mint-50",
  "mint-100",
  "mint-200",
  "mint-300",
  "mint-400",
  "mint-500",
  "mint-600",
  "mint-700",
  "mint-800",
  "mint-900",
  "pink-0",
  "pink-50",
  "pink-100",
  "pink-200",
  "pink-300",
  "pink-400",
  "pink-500",
  "pink-600",
  "pink-700",
  "pink-800",
  "pink-900",
  "yellow-0",
  "yellow-50",
  "yellow-100",
  "yellow-200",
  "yellow-300",
  "yellow-400",
  "yellow-500",
  "yellow-600",
  "yellow-700",
  "yellow-800",
  "yellow-900",
  "green-0",
  "green-50",
  "green-100",
  "green-200",
  "green-300",
  "green-400",
  "green-500",
  "green-600",
  "green-700",
  "green-800",
  "green-900",
  "red-0",
  "red-50",
  "red-100",
  "red-200",
  "red-300",
  "red-400",
  "red-500",
  "red-600",
  "red-700",
  "red-800",
  "red-900",
  "amber-0",
  "amber-50",
  "amber-100",
  "amber-200",
  "amber-300",
  "amber-400",
  "amber-500",
  "amber-600",
  "amber-700",
  "amber-800",
  "amber-900",
  "sky-0",
  "sky-50",
  "sky-100",
  "sky-200",
  "sky-300",
  "sky-400",
  "sky-500",
  "sky-600",
  "sky-700",
  "sky-800",
  "sky-900",
  "alpha-stone-0",
  "alpha-stone-50",
  "alpha-stone-100",
  "alpha-stone-200",
  "alpha-stone-300",
  "alpha-stone-400",
  "alpha-stone-500",
  "alpha-stone-600",
  "alpha-stone-700",
  "alpha-stone-800",
  "alpha-stone-900",
  "alpha-contrast-0",
  "alpha-contrast-50",
  "alpha-contrast-100",
  "alpha-contrast-200",
  "alpha-contrast-300",
  "alpha-contrast-400",
  "alpha-contrast-500",
  "alpha-contrast-600",
  "alpha-contrast-700",
  "alpha-contrast-800",
  "alpha-contrast-900",
  "alpha-inverse-0",
  "alpha-inverse-50",
  "alpha-inverse-100",
  "alpha-inverse-200",
  "alpha-inverse-300",
  "alpha-inverse-400",
  "alpha-inverse-500",
  "alpha-inverse-600",
  "alpha-inverse-700",
  "alpha-inverse-800",
  "alpha-inverse-900",
  "alpha-black-0",
  "alpha-black-50",
  "alpha-black-100",
  "alpha-black-200",
  "alpha-black-300",
  "alpha-black-400",
  "alpha-black-500",
  "alpha-black-600",
  "alpha-black-700",
  "alpha-black-800",
  "alpha-black-900",
  "alpha-white-0",
  "alpha-white-50",
  "alpha-white-100",
  "alpha-white-200",
  "alpha-white-300",
  "alpha-white-400",
  "alpha-white-500",
  "alpha-white-600",
  "alpha-white-700",
  "alpha-white-800",
  "alpha-white-900",
  "background-primary",
  "background-secondary",
  "background-tertiary",
  "background-disabled",
  "background-inverse-primary",
  "background-inverse-secondary",
  "background-inverse-disabled",
  "background-accent-subtle",
  "background-accent-base",
  "background-success-subtle",
  "background-success-base",
  "background-warning-subtle",
  "background-warning-base",
  "background-error-subtle",
  "background-error-base",
  "background-info-subtle",
  "background-info-base",
  "background-static-white",
  "background-static-black",
  "background-brand-purple-subtle",
  "background-brand-purple-base",
  "background-brand-mint-subtle",
  "background-brand-mint-base",
  "background-brand-pink-subtle",
  "background-brand-pink-base",
  "background-brand-yellow-subtle",
  "background-brand-yellow-base",
  "text-primary",
  "text-secondary",
  "text-tertiary",
  "text-disabled",
  "text-inverse-primary",
  "text-inverse-secondary",
  "text-inverse-tertiary",
  "text-alpha-disabled",
  "text-on-color",
  "text-accent",
  "text-success",
  "text-warning",
  "text-error",
  "text-info",
  "text-static-black",
  "text-static-white",
  "text-link-default",
  "text-link-hover",
  "text-link-visited",
  "text-link-disabled",
  "text-brand-purple",
  "text-brand-mint",
  "text-brand-pink",
  "text-brand-yellow",
  "icon-primary",
  "icon-secondary",
  "icon-tertiary",
  "icon-disabled",
  "icon-inverse-primary",
  "icon-inverse-secondary",
  "icon-inverse-tertiary",
  "icon-inverse-disabled",
  "icon-on-color",
  "icon-accent",
  "icon-success",
  "icon-warning",
  "icon-error",
  "icon-info",
  "icon-static-black",
  "icon-static-white",
  "icon-brand-purple",
  "icon-brand-mint",
  "icon-brand-pink",
  "icon-brand-yellow",
  "border-primary",
  "border-secondary",
  "border-tertiary",
  "border-strong",
  "border-disabled",
  "border-focus",
  "border-inverse-primary",
  "border-inverse-secondary",
  "border-inverse-strong",
  "border-inverse-disabled",
  "border-inverse-focus",
  "border-static-white",
  "border-static-black",
  "border-accent-subtle",
  "border-accent-base",
  "border-success-subtle",
  "border-success-base",
  "border-warning-subtle",
  "border-warning-base",
  "border-error-subtle",
  "border-error-base",
  "border-info-subtle",
  "border-info-base",
  "border-brand-purple-subtle",
  "border-brand-purple-base",
  "border-brand-mint-subtle",
  "border-brand-mint-base",
  "border-brand-pink-subtle",
  "border-brand-pink-base",
  "border-brand-yellow-subtle",
  "border-brand-yellow-base",
  "scrim-contrast-subtle",
  "scrim-contrast-base",
  "scrim-inverse-subtle",
  "scrim-inverse-base",
  "state-neutral-hover",
  "state-neutral-active",
  "state-contrast-hover",
  "state-contrast-active",
  "state-inverse-hover",
  "state-inverse-active",
  "tint-neutral-100",
  "tint-neutral-200",
  "tint-neutral-300",
  "tint-neutral-400",
  "tint-contrast-100",
  "tint-contrast-200",
  "tint-contrast-300",
  "tint-contrast-400",
  "tint-inverse-100",
  "tint-inverse-200",
  "tint-inverse-300",
  "tint-inverse-400",
];

/** `--spacing-vesper-*` */
const SPACING = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "8",
  "10",
  "12",
  "14",
  "16",
  "20",
  "24",
  "28",
  "32",
  "40",
  "half",
  "micro",
];

/** `--border-width-vesper-*` */
const BORDER_WIDTH = ["base", "strong"];

/** `--outline-width-vesper-*` */
const OUTLINE_WIDTH = ["base", "strong"];

/** `--radius-vesper-*` */
const RADIUS = ["1", "2", "3", "4", "6", "7", "half"];

/** `--tracking-vesper-*` */
const TRACKING = [
  "tightest",
  "tighter",
  "tight",
  "normal",
  "wide",
  "wider",
  "widest",
];

/** `--leading-vesper-*` */
const LEADING = ["none", "tight", "snug", "normal", "relaxed", "loose"];

/** `--font-vesper-*` */
const FONT = ["sans", "mono"];

/** `--shadow-vesper-*` */
const SHADOW = [
  "100",
  "200",
  "300",
  "400",
  "inset-100",
  "inset-200",
  "focus-ring",
];

/** `--transition-duration-vesper-*` */
const TRANSITION_DURATION = ["fast", "default", "slow"];

describe("withVesper", () => {
  test("does not change the merging of default tailwind classes", () => {
    expect(twMerge("p-2 p-4 bg-red-500 bg-blue-500")).toBe("p-4 bg-blue-500");
    expect(twMerge("border-2 border-red-500")).toBe("border-2 border-red-500");
    expect(twMerge("shadow-md shadow-red-500")).toBe(
      "shadow-md shadow-red-500",
    );
  });

  test("can be combined with other config extensions", () => {
    const customTwMerge = extendTailwindMerge(
      { extend: { theme: { spacing: ["gutter"] } } },
      withVesper,
    );

    expect(customTwMerge("p-gutter p-vesper-4")).toBe("p-vesper-4");
    expect(customTwMerge("p-vesper-4 p-gutter")).toBe("p-gutter");
  });

  describe("theme variables", () => {
    test.each(COLOR)("--color-vesper-%s", (name) => {
      expect(twMerge(`text-red-500 text-vesper-${name}`)).toBe(
        `text-vesper-${name}`,
      );
      expect(twMerge(`bg-red-500 bg-vesper-${name}`)).toBe(`bg-vesper-${name}`);
      expect(twMerge(`border-vesper-base border-vesper-${name}`)).toBe(
        `border-vesper-base border-vesper-${name}`,
      );
    });

    test.each(SPACING)("--spacing-vesper-%s", (name) => {
      expect(twMerge(`p-1 p-vesper-${name}`)).toBe(`p-vesper-${name}`);
      expect(twMerge(`p-vesper-${name} px-1`)).toBe(`p-vesper-${name} px-1`);
      expect(twMerge(`-mt-1 -mt-vesper-${name}`)).toBe(`-mt-vesper-${name}`);
    });

    test.each(BORDER_WIDTH)("--border-width-vesper-%s", (name) => {
      expect(twMerge(`border-2 border-vesper-${name}`)).toBe(
        `border-vesper-${name}`,
      );
      expect(twMerge(`border-x-2 border-x-vesper-${name}`)).toBe(
        `border-x-vesper-${name}`,
      );
      expect(twMerge(`divide-y-2 divide-y-vesper-${name}`)).toBe(
        `divide-y-vesper-${name}`,
      );
      expect(
        twMerge(`border-vesper-${name} border-vesper-border-primary`),
      ).toBe(`border-vesper-${name} border-vesper-border-primary`);
    });

    test.each(OUTLINE_WIDTH)("--outline-width-vesper-%s", (name) => {
      expect(twMerge(`outline-2 outline-vesper-${name}`)).toBe(
        `outline-vesper-${name}`,
      );
      expect(
        twMerge(`outline-vesper-${name} outline-vesper-border-focus`),
      ).toBe(`outline-vesper-${name} outline-vesper-border-focus`);
    });

    test.each(RADIUS)("--radius-vesper-%s", (name) => {
      expect(twMerge(`rounded-md rounded-vesper-${name}`)).toBe(
        `rounded-vesper-${name}`,
      );
      expect(twMerge(`rounded-t-md rounded-t-vesper-${name}`)).toBe(
        `rounded-t-vesper-${name}`,
      );
    });

    test.each(TRACKING)("--tracking-vesper-%s", (name) => {
      expect(twMerge(`tracking-wide tracking-vesper-${name}`)).toBe(
        `tracking-vesper-${name}`,
      );
    });

    test.each(LEADING)("--leading-vesper-%s", (name) => {
      expect(twMerge(`leading-5 leading-vesper-${name}`)).toBe(
        `leading-vesper-${name}`,
      );
    });

    test.each(FONT)("--font-vesper-%s", (name) => {
      expect(twMerge(`font-mono font-vesper-${name}`)).toBe(
        `font-vesper-${name}`,
      );
      expect(twMerge(`font-vesper-${name} font-bold`)).toBe(
        `font-vesper-${name} font-bold`,
      );
    });

    test.each(SHADOW)("--shadow-vesper-%s", (name) => {
      expect(twMerge(`shadow-md shadow-vesper-${name}`)).toBe(
        `shadow-vesper-${name}`,
      );
      expect(twMerge(`shadow-vesper-${name} shadow-vesper-stone-500`)).toBe(
        `shadow-vesper-${name} shadow-vesper-stone-500`,
      );
    });

    test.each(TRANSITION_DURATION)(
      "--transition-duration-vesper-%s",
      (name) => {
        expect(twMerge(`duration-100 duration-vesper-${name}`)).toBe(
          `duration-vesper-${name}`,
        );
      },
    );
  });

  describe("utilities", () => {
    describe("vesper.bg-vesper-dot-pattern", () => {
      test.each([
        "bg-vesper-dot-pattern-primary",
        "bg-vesper-dot-pattern-secondary",
        "bg-vesper-dot-pattern-tertiary",
        ...COLOR.map((name) => `bg-vesper-dot-pattern-${name}`),
        "bg-vesper-dot-pattern-inverse",
        ...COLOR.map((name) => `bg-vesper-dot-pattern-inverse-${name}`),
      ])("%s", (utility) => {
        expect(twMerge(`bg-vesper-dot-pattern-primary ${utility}`)).toBe(
          utility,
        );
        expect(twMerge(`bg-red-500 ${utility}`)).toBe(utility);
        expect(twMerge(`${utility} bg-red-500`)).toBe(`${utility} bg-red-500`);
        expect(twMerge(`bg-none ${utility}`)).toBe(utility);
        expect(twMerge(`${utility} bg-none`)).toBe(`${utility} bg-none`);
        expect(twMerge(`bg-bottom ${utility}`)).toBe(utility);
        expect(twMerge(`${utility} bg-bottom`)).toBe(`${utility} bg-bottom`);
        expect(twMerge(`bg-repeat-x ${utility}`)).toBe(utility);
        expect(twMerge(`${utility} bg-repeat-x`)).toBe(
          `${utility} bg-repeat-x`,
        );
      });
    });
  });
});
