import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import { DesignTokenTree, parseDesignTokenTree } from "./utils";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const AUTO_GENERATED_WARNING_JS = `/**
 * THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:
 *
 * \`yarn generate:colors\`
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 */`;

const AUTO_GENERATED_WARNING_CSS = `/* ========================================================
THIS FILE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:colors

DO NOT EDIT THIS FILE DIRECTLY
======================================================== */`;

const LEGACY_TOKENS = ["old--stoneA"];

type ColorTokenValue = {
  colorSpace: string;
  components: number[];
  alpha: number;
  hex: string;
};

const parseColorTokenTree = (tree: DesignTokenTree<ColorTokenValue>) =>
  parseDesignTokenTree(
    tree,
    (name, token) => {
      if (token.$value.alpha === 0) {
        return [name, "transparent"];
      }

      if (token.$value.alpha < 1) {
        const rgba = token.$value.components
          .map((c) => Math.round(c * 255))
          .concat(Number(token.$value.alpha.toFixed(3)));

        return [name, `rgba(${rgba.join(", ")})`];
      }

      return [name, token.$value.hex.toLowerCase()];
    },
    (tokenName) => !LEGACY_TOKENS.some((legacy) => tokenName.includes(legacy)),
  );

const darkJSON: DesignTokenTree<ColorTokenValue> = JSON.parse(
  fs.readFileSync(
    path.resolve(__dirname, "../assets/Dark.tokens.json"),
    "utf-8",
  ),
);

const lightJSON: DesignTokenTree<ColorTokenValue> = JSON.parse(
  fs.readFileSync(
    path.resolve(__dirname, "../assets/Light.tokens.json"),
    "utf-8",
  ),
);

const darkTokens = parseColorTokenTree(darkJSON);
const lightTokens = parseColorTokenTree(lightJSON);

fs.writeFileSync(
  path.resolve(__dirname, "../src/colors.ts"),
  `${AUTO_GENERATED_WARNING_JS}

  export const colors = ${JSON.stringify({
    dark: darkTokens,
    light: lightTokens,
  })}`,
);

const lightModeCSSVars = Object.entries(lightTokens)
  .map((token) => {
    const [name, value] = token;
    return `--${name}: ${value};`;
  })
  .join("\n");

const darkModeCSSVars = Object.entries(darkTokens)
  .map((token) => {
    const [name, value] = token;
    return `--${name}: ${value};`;
  })
  .join("\n");

const cssFileContents = [
  `:root { ${lightModeCSSVars} }`,
  `@media (prefers-color-scheme: dark) { :root { ${darkModeCSSVars} }  }`,
  `.light-mode { ${lightModeCSSVars} }`,
  `.dark-mode { ${darkModeCSSVars} }`,
].join("\n\n");

fs.writeFileSync(
  path.resolve(__dirname, "../src/colors.css"),
  `${AUTO_GENERATED_WARNING_CSS}

  ${cssFileContents}`,
);
