import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import { DesignTokenTree, parseDesignTokenTree } from "./utils";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const AUTO_GENERATED_WARNING_JS = `/**
 * THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:
 *
 * \`yarn generate:tracking\`
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 */`;

const AUTO_GENERATED_WARNING_CSS = `/* ========================================================
THIS FILE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:tracking

DO NOT EDIT THIS FILE DIRECTLY
======================================================== */`;

const spacingJSON: DesignTokenTree<number> = JSON.parse(
  fs.readFileSync(
    path.resolve(__dirname, "../assets/Tracking.tokens.json"),
    "utf-8",
  ),
);

const trackingTokens = parseDesignTokenTree({
  tree: spacingJSON,
  processToken: (name, token) => [name.toLowerCase(), `${token.$value}px`],
});

fs.writeFileSync(
  path.resolve(__dirname, "../src/tracking.ts"),
  `${AUTO_GENERATED_WARNING_JS}

  export const tracking = ${JSON.stringify(trackingTokens)}`,
);

const cssFileContents = `:root {
  ${Object.entries(trackingTokens)
    .map((entry) => {
      const [name, value] = entry;
      return `--tracking-${name}: ${value};`;
    })
    .join("\n")}
}`;

fs.writeFileSync(
  path.resolve(__dirname, "../src/tracking.css"),
  `${AUTO_GENERATED_WARNING_CSS}

  ${cssFileContents}`,
);
