import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import { DesignTokenTree, parseDesignTokenTree } from "./utils";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const AUTO_GENERATED_WARNING_JS = `/**
 * THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:
 *
 * \`yarn generate:leading\`
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 */`;

const AUTO_GENERATED_WARNING_CSS = `/* ========================================================
THIS FILE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:

yarn generate:leading

DO NOT EDIT THIS FILE DIRECTLY
======================================================== */`;

const spacingJSON: DesignTokenTree<number> = JSON.parse(
  fs.readFileSync(
    path.resolve(__dirname, "../assets/Leading.tokens.json"),
    "utf-8",
  ),
);

const leadingTokens = parseDesignTokenTree(spacingJSON, (name, token) => [
  name.toLowerCase(),
  `${token.$value}%`,
]);

fs.writeFileSync(
  path.resolve(__dirname, "../src/leading.ts"),
  `${AUTO_GENERATED_WARNING_JS}

  export const leading = ${JSON.stringify(leadingTokens)}`,
);

const cssFileContents = `:root {
  ${Object.entries(leadingTokens)
    .map((entry) => {
      const [name, value] = entry;
      return `--leading-${name}: ${value};`;
    })
    .join("\n")}
}`;

fs.writeFileSync(
  path.resolve(__dirname, "../src/leading.css"),
  `${AUTO_GENERATED_WARNING_CSS}

  ${cssFileContents}`,
);
