/**
 * THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:
 *
 * `yarn generate:icons`
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 */

import type { ComponentProps } from "react";

export const Icon_warning = (props: ComponentProps<"svg">) => {
  return (
    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" {...props}>
      <path
        d="M13.0423 16.3788V17.4091L12.5259 17.9242H11.4932L10.9769 17.4091V16.3788L11.4932 15.8636H12.5259L13.0423 16.3788Z"
        fill="currentColor"
      ></path>
      <path
        d="M13.3005 8.13636L12.7841 14.3182L12.2678 14.8333H11.7514L11.235 14.3182L10.7187 8.13636L11.235 7.62121H12.7841L13.3005 8.13636Z"
        fill="currentColor"
      ></path>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M22 17.7522L20.4096 20.5H3.57229L2 17.7844L10.5018 3.5H13.5173L22 17.7522ZM3.19712 17.7914L4.16832 19.4697H19.8135L20.8029 17.7592L12.9294 4.5303H11.0898L3.19712 17.7914Z"
        fill="currentColor"
      ></path>
    </svg>
  );
};
