/**
 * THIS CODE IS AUTO-GENERATED BY RUNNING THE FOLLOWING COMMAND IN THE MONOREPO ROOT:
 *
 * `yarn generate:icons`
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 */

import { Icon_add } from "./Icon_add";
import { Icon_ai_agent_solid } from "./Icon_ai_agent_solid";
import { Icon_ai_agent } from "./Icon_ai_agent";
import { Icon_ai_data } from "./Icon_ai_data";
import { Icon_ai_model } from "./Icon_ai_model";
import { Icon_ai_task } from "./Icon_ai_task";
import { Icon_ai_video_gen } from "./Icon_ai_video_gen";
import { Icon_ai } from "./Icon_ai";
import { Icon_arrow_down } from "./Icon_arrow_down";
import { Icon_arrow_left } from "./Icon_arrow_left";
import { Icon_arrow_right } from "./Icon_arrow_right";
import { Icon_arrow_up_left } from "./Icon_arrow_up_left";
import { Icon_arrow_up_right } from "./Icon_arrow_up_right";
import { Icon_arrow_up } from "./Icon_arrow_up";
import { Icon_auto } from "./Icon_auto";
import { Icon_blackhole } from "./Icon_blackhole";
import { Icon_board } from "./Icon_board";
import { Icon_caret_down } from "./Icon_caret_down";
import { Icon_caret_left } from "./Icon_caret_left";
import { Icon_caret_right } from "./Icon_caret_right";
import { Icon_caret_up } from "./Icon_caret_up";
import { Icon_cart } from "./Icon_cart";
import { Icon_chat_solid } from "./Icon_chat_solid";
import { Icon_chat } from "./Icon_chat";
import { Icon_checkmark } from "./Icon_checkmark";
import { Icon_chip } from "./Icon_chip";
import { Icon_circle_x_solid } from "./Icon_circle_x_solid";
import { Icon_circle_x } from "./Icon_circle_x";
import { Icon_close } from "./Icon_close";
import { Icon_cloud_server_solid } from "./Icon_cloud_server_solid";
import { Icon_cloud_server } from "./Icon_cloud_server";
import { Icon_copy } from "./Icon_copy";
import { Icon_document_solid } from "./Icon_document_solid";
import { Icon_document } from "./Icon_document";
import { Icon_download } from "./Icon_download";
import { Icon_error_solid } from "./Icon_error_solid";
import { Icon_error } from "./Icon_error";
import { Icon_folder } from "./Icon_folder";
import { Icon_galaxy_rack } from "./Icon_galaxy_rack";
import { Icon_galaxy } from "./Icon_galaxy";
import { Icon_globe } from "./Icon_globe";
import { Icon_info_solid } from "./Icon_info_solid";
import { Icon_info } from "./Icon_info";
import { Icon_link } from "./Icon_link";
import { Icon_location } from "./Icon_location";
import { Icon_loudbox } from "./Icon_loudbox";
import { Icon_menu } from "./Icon_menu";
import { Icon_minus } from "./Icon_minus";
import { Icon_mode_dark } from "./Icon_mode_dark";
import { Icon_mode_light } from "./Icon_mode_light";
import { Icon_mode_system } from "./Icon_mode_system";
import { Icon_model_deepseek_color } from "./Icon_model_deepseek_color";
import { Icon_model_deepseek } from "./Icon_model_deepseek";
import { Icon_model_falcon_color } from "./Icon_model_falcon_color";
import { Icon_model_falcon } from "./Icon_model_falcon";
import { Icon_model_google_color } from "./Icon_model_google_color";
import { Icon_model_google } from "./Icon_model_google";
import { Icon_model_llama_color } from "./Icon_model_llama_color";
import { Icon_model_llama } from "./Icon_model_llama";
import { Icon_model_openai } from "./Icon_model_openai";
import { Icon_model_qwen_color } from "./Icon_model_qwen_color";
import { Icon_model_qwen } from "./Icon_model_qwen";
import { Icon_monitor } from "./Icon_monitor";
import { Icon_org_developer } from "./Icon_org_developer";
import { Icon_org_experience } from "./Icon_org_experience";
import { Icon_org_operations } from "./Icon_org_operations";
import { Icon_org_systems } from "./Icon_org_systems";
import { Icon_org_university } from "./Icon_org_university";
import { Icon_phone } from "./Icon_phone";
import { Icon_quasar } from "./Icon_quasar";
import { Icon_quietbox } from "./Icon_quietbox";
import { Icon_reset } from "./Icon_reset";
import { Icon_search } from "./Icon_search";
import { Icon_server_solid } from "./Icon_server_solid";
import { Icon_server } from "./Icon_server";
import { Icon_shield_solid } from "./Icon_shield_solid";
import { Icon_shield } from "./Icon_shield";
import { Icon_size } from "./Icon_size";
import { Icon_social_apple } from "./Icon_social_apple";
import { Icon_social_discord } from "./Icon_social_discord";
import { Icon_social_facebook } from "./Icon_social_facebook";
import { Icon_social_github } from "./Icon_social_github";
import { Icon_social_google } from "./Icon_social_google";
import { Icon_social_linkedin } from "./Icon_social_linkedin";
import { Icon_social_microsoft } from "./Icon_social_microsoft";
import { Icon_social_x } from "./Icon_social_x";
import { Icon_social_youtube } from "./Icon_social_youtube";
import { Icon_success_solid } from "./Icon_success_solid";
import { Icon_success } from "./Icon_success";
import { Icon_tensix } from "./Icon_tensix";
import { Icon_tenstorrent } from "./Icon_tenstorrent";
import { Icon_trash_solid } from "./Icon_trash_solid";
import { Icon_trash } from "./Icon_trash";
import { Icon_tt_forge_fe } from "./Icon_tt_forge_fe";
import { Icon_tt_forge } from "./Icon_tt_forge";
import { Icon_tt_llk } from "./Icon_tt_llk";
import { Icon_tt_metalium } from "./Icon_tt_metalium";
import { Icon_tt_nn } from "./Icon_tt_nn";
import { Icon_tt_torch } from "./Icon_tt_torch";
import { Icon_tt_xla } from "./Icon_tt_xla";
import { Icon_upload } from "./Icon_upload";
import { Icon_user_multiple_solid } from "./Icon_user_multiple_solid";
import { Icon_user_multiple } from "./Icon_user_multiple";
import { Icon_user_solid } from "./Icon_user_solid";
import { Icon_user } from "./Icon_user";
import { Icon_warning_solid } from "./Icon_warning_solid";
import { Icon_warning } from "./Icon_warning";
import { Icon_wormhole } from "./Icon_wormhole";

export const registry = {
  add: Icon_add,
  "ai-agent-solid": Icon_ai_agent_solid,
  "ai-agent": Icon_ai_agent,
  "ai-data": Icon_ai_data,
  "ai-model": Icon_ai_model,
  "ai-task": Icon_ai_task,
  "ai-video-gen": Icon_ai_video_gen,
  ai: Icon_ai,
  "arrow-down": Icon_arrow_down,
  "arrow-left": Icon_arrow_left,
  "arrow-right": Icon_arrow_right,
  "arrow-up-left": Icon_arrow_up_left,
  "arrow-up-right": Icon_arrow_up_right,
  "arrow-up": Icon_arrow_up,
  auto: Icon_auto,
  blackhole: Icon_blackhole,
  board: Icon_board,
  "caret-down": Icon_caret_down,
  "caret-left": Icon_caret_left,
  "caret-right": Icon_caret_right,
  "caret-up": Icon_caret_up,
  cart: Icon_cart,
  "chat-solid": Icon_chat_solid,
  chat: Icon_chat,
  checkmark: Icon_checkmark,
  chip: Icon_chip,
  "circle-x-solid": Icon_circle_x_solid,
  "circle-x": Icon_circle_x,
  close: Icon_close,
  "cloud-server-solid": Icon_cloud_server_solid,
  "cloud-server": Icon_cloud_server,
  copy: Icon_copy,
  "document-solid": Icon_document_solid,
  document: Icon_document,
  download: Icon_download,
  "error-solid": Icon_error_solid,
  error: Icon_error,
  folder: Icon_folder,
  "galaxy-rack": Icon_galaxy_rack,
  galaxy: Icon_galaxy,
  globe: Icon_globe,
  "info-solid": Icon_info_solid,
  info: Icon_info,
  link: Icon_link,
  location: Icon_location,
  loudbox: Icon_loudbox,
  menu: Icon_menu,
  minus: Icon_minus,
  "mode-dark": Icon_mode_dark,
  "mode-light": Icon_mode_light,
  "mode-system": Icon_mode_system,
  "model-deepseek-color": Icon_model_deepseek_color,
  "model-deepseek": Icon_model_deepseek,
  "model-falcon-color": Icon_model_falcon_color,
  "model-falcon": Icon_model_falcon,
  "model-google-color": Icon_model_google_color,
  "model-google": Icon_model_google,
  "model-llama-color": Icon_model_llama_color,
  "model-llama": Icon_model_llama,
  "model-openai": Icon_model_openai,
  "model-qwen-color": Icon_model_qwen_color,
  "model-qwen": Icon_model_qwen,
  monitor: Icon_monitor,
  "org-developer": Icon_org_developer,
  "org-experience": Icon_org_experience,
  "org-operations": Icon_org_operations,
  "org-systems": Icon_org_systems,
  "org-university": Icon_org_university,
  phone: Icon_phone,
  quasar: Icon_quasar,
  quietbox: Icon_quietbox,
  reset: Icon_reset,
  search: Icon_search,
  "server-solid": Icon_server_solid,
  server: Icon_server,
  "shield-solid": Icon_shield_solid,
  shield: Icon_shield,
  size: Icon_size,
  "social-apple": Icon_social_apple,
  "social-discord": Icon_social_discord,
  "social-facebook": Icon_social_facebook,
  "social-github": Icon_social_github,
  "social-google": Icon_social_google,
  "social-linkedin": Icon_social_linkedin,
  "social-microsoft": Icon_social_microsoft,
  "social-x": Icon_social_x,
  "social-youtube": Icon_social_youtube,
  "success-solid": Icon_success_solid,
  success: Icon_success,
  tensix: Icon_tensix,
  tenstorrent: Icon_tenstorrent,
  "trash-solid": Icon_trash_solid,
  trash: Icon_trash,
  "tt-forge-fe": Icon_tt_forge_fe,
  "tt-forge": Icon_tt_forge,
  "tt-llk": Icon_tt_llk,
  "tt-metalium": Icon_tt_metalium,
  "tt-nn": Icon_tt_nn,
  "tt-torch": Icon_tt_torch,
  "tt-xla": Icon_tt_xla,
  upload: Icon_upload,
  "user-multiple-solid": Icon_user_multiple_solid,
  "user-multiple": Icon_user_multiple,
  "user-solid": Icon_user_solid,
  user: Icon_user,
  "warning-solid": Icon_warning_solid,
  warning: Icon_warning,
  wormhole: Icon_wormhole,
};
