/**
 * Extracts every `tsx demo` code block in the monorepo root `docs/` folder
 * into a real module under `src/generated-demos/`
 *
 * `remark-tsx-demos.mts` then imports those modules back into the document,
 * so a demo renders right above its own code block
 */

import type { Nodes } from "mdast";
import { watch } from "node:fs";
import {
  mkdir,
  readdir,
  readFile,
  rm,
  rmdir,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import remarkFrontmatter from "remark-frontmatter";
import remarkGfm from "remark-gfm";
import remarkMdx from "remark-mdx";
import remarkParse from "remark-parse";
import { unified } from "unified";

import {
  DEMOS_ROOT,
  DOC_FILE_EXT,
  DOCS_ROOT,
  getDemoDocPath,
  getDemoModulePath,
  isDemoCodeBlock,
} from "../src/lib/mdx/demos.mts";

/**
 * Header prepended to every generated module
 *
 * Demos are rendered from a server component (see `src/app/[...doc]`) and are
 * interactive by nature (state, event handlers), so must be client components
 */
const AUTO_GENERATED_WARNING = [
  "// THIS CODE IS AUTO-GENERATED by `apps/website/scripts/generate-demos.ts`",
  "// DO NOT EDIT THIS FILE DIRECTLY",
  "",
  '"use client";',
  "",
].join("\n");

/** Every `.md`/`.mdx` file in `docs/`, as absolute paths */
const getDocsPaths = async (): Promise<string[]> => {
  const entries = await readdir(DOCS_ROOT, { recursive: true });

  return entries
    .filter((entry) => DOC_FILE_EXT.test(entry))
    .map((entry) => path.join(DOCS_ROOT, entry));
};

// Documents are parsed here, not compiled, so
// we only need the plugins that change syntax
const parser = unified()
  .use(remarkParse)
  .use(remarkMdx)
  .use(remarkGfm)
  .use(remarkFrontmatter);

/** Get a markdown file's `tsx demo` code blocks contents */
const getDemosSources = (markdown: string): string[] => {
  const sources: string[] = [];

  const visit = (node: Nodes): void => {
    if ("children" in node) node.children.forEach(visit);
    if (isDemoCodeBlock(node)) sources.push(node.value);
  };
  visit(parser.parse(markdown));

  return sources;
};

/**
 * Write to a file, skipping the write when it is already up to date
 *
 * Generated demos live inside the app, so rewriting one that did not
 * change would restart next's dev server for nothing (and bust turbo's cache)
 */
const createOrUpdateFile = async (filePath: string, content: string) => {
  const current = await readFile(filePath, "utf-8").catch(() => null);
  if (current === content) return;

  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content, "utf-8");
};

/** Generate every document's demos, and delete stale modules from previous runs */
const generateDemos = async (): Promise<{
  generated: number;
  failed: number;
}> => {
  const generatedDemos = new Set<string>();
  const failedDemos = new Set<string>();

  for (const docFilePath of await getDocsPaths()) {
    const markdown = await readFile(docFilePath, "utf-8");

    let demosSources: string[];

    try {
      demosSources = getDemosSources(markdown);
    } catch (error) {
      failedDemos.add(docFilePath);

      const relativeDocPath = path.relative(DOCS_ROOT, docFilePath);
      const errorMessage = error instanceof Error ? error.message : error;
      console.error(`skipped ${relativeDocPath} - ${errorMessage}`);

      continue;
    }

    for (const [index, source] of demosSources.entries()) {
      const modulePath = getDemoModulePath(docFilePath, index);
      if (!modulePath) continue;

      generatedDemos.add(modulePath);
      await createOrUpdateFile(
        modulePath,
        `${AUTO_GENERATED_WARNING}\n${source.trim()}\n`,
      );
    }
  }

  const demoFiles = await readdir(DEMOS_ROOT, {
    recursive: true,
    withFileTypes: true,
  }).catch(() => []);

  // Delete demo files that are no longer used
  for (const demoFile of demoFiles) {
    const entryPath = path.join(demoFile.parentPath, demoFile.name);
    if (!demoFile.isFile() || generatedDemos.has(entryPath)) continue;

    // A document that couldn't be parsed still owns the previous modules it generated
    // from a successful run, so we shouldn't delete demos from docs that fail to parse
    const docPath = getDemoDocPath(entryPath);
    if (docPath && failedDemos.has(docPath)) continue;

    await rm(entryPath);
  }

  // Delete empty directories, deepest first, so a folder holding nothing but empty folders goes too
  for (const demoDir of demoFiles.reverse()) {
    if (!demoDir.isDirectory()) continue;

    const dirPath = path.join(demoDir.parentPath, demoDir.name);
    await rmdir(dirPath).catch(() => {}); // throws while it holds anything
  }

  return { generated: generatedDemos.size, failed: failedDemos.size };
};

const isDevMode = process.argv.includes("--watch");

/**
 * Terminate the process with a non-zero exit code,
 * only if we are not using the `--watch` flag
 *
 * This will cause non-development builds with unsuccessful demo generation
 * to fail, but will not stop us in development
 * */
const failProductionBuild = () => {
  if (!isDevMode) process.exitCode = 1;
};

let currentRun: Promise<void> = Promise.resolve();

/**
 * Generate demos, one run at a time
 *
 * A run is queued behind the one in flight, so a burst of edits can never have
 * two of them writing (and pruning) the same modules at once
 */
const run = (): Promise<void> => {
  currentRun = currentRun.then(async () => {
    try {
      const { generated, failed } = await generateDemos();

      console.log(`Generated demos: ${generated}`);

      if (failed) {
        console.log(`Failed demos: ${failed}`);
        failProductionBuild();
      }
    } catch (error) {
      console.error(error);
      failProductionBuild();
    }
  });

  return currentRun;
};

await run();

if (isDevMode) {
  let timeout: NodeJS.Timeout | undefined;

  watch(DOCS_ROOT, { recursive: true }, (_event, filename) => {
    if (!filename || !DOC_FILE_EXT.test(filename)) return;

    clearTimeout(timeout);
    timeout = setTimeout(run, 50);
  });

  console.log(`Watching ${path.relative(process.cwd(), DOCS_ROOT)} for demos`);
}
