/**
 * extracts every ` ```tsx demo ` code block in the monorepo root `docs/` folder
 * into a real module under `src/generated-demos/`
 *
 * `src/lib/mdx/remark-tsx-demos.mts` then imports those modules back into the
 * document, so a demo renders right above the code block it was written as -
 * one source of truth for both the running example and the code shown for it
 *
 * documents are parsed with the same markdown/MDX syntax the site compiles
 * them with, so both halves see the same code blocks in the same order (see
 * `src/lib/mdx/demos.mts`)
 *
 * run with `yarn workspace website generate:demos` (or `--watch` to keep the
 * generated modules in sync while writing docs)
 */

import type { Nodes } from "mdast";
import { watch } from "node:fs";
import {
  mkdir,
  readdir,
  readFile,
  rm,
  rmdir,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import remarkFrontmatter from "remark-frontmatter";
import remarkGfm from "remark-gfm";
import remarkMdx from "remark-mdx";
import remarkParse from "remark-parse";
import { unified } from "unified";

import {
  demoModulePath,
  DEMOS_ROOT,
  DOCS_ROOT,
  isDemoCodeBlock,
} from "../src/lib/mdx/demos.mts";

/**
 * documents are only parsed here (never compiled), so this needs the plugins
 * that change *syntax* - the ones in `next.config.ts` that only rewrite nodes
 * (links, alerts, JSX children) can not add or remove code blocks
 */
const parser = unified()
  .use(remarkParse)
  .use(remarkMdx)
  .use(remarkGfm)
  .use(remarkFrontmatter);

/**
 * header prepended to every generated module
 *
 * demos are rendered from a server component (see `src/app/[...doc]`) and are
 * interactive by nature (state, event handlers), so they are generated as
 * client components
 */
const BANNER = [
  "// GENERATED by `apps/website/scripts/generate-demos.ts` - do not edit",
  "//",
  "// edit the `tsx demo` code block this was extracted from instead",
  "",
  '"use client";',
  "",
].join("\n");

/** every `.mdx` file in `docs/`, as absolute paths */
const documents = async (): Promise<string[]> => {
  const entries = await readdir(DOCS_ROOT, { recursive: true });

  return entries
    .filter((entry) => entry.endsWith(".mdx"))
    .map((entry) => path.join(DOCS_ROOT, entry));
};

/** a document's demo sources, in document order */
const demoSources = (markdown: string): string[] => {
  const sources: string[] = [];

  const visit = (node: Nodes): void => {
    if ("children" in node) node.children.forEach(visit);

    if (node.type === "code" && isDemoCodeBlock(node.lang, node.meta)) {
      sources.push(node.value);
    }
  };

  visit(parser.parse(markdown));

  return sources;
};

/**
 * write a module, skipping the write when it is already up to date
 *
 * the generated modules live inside the app, so rewriting one that did not
 * change would restart next's dev server for nothing (and bust turbo's cache)
 */
const writeModule = async (filePath: string, content: string) => {
  const current = await readFile(filePath, "utf-8").catch(() => null);
  if (current === content) return;

  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content, "utf-8");
};

/** generate every document's demos, and delete the modules left behind */
const generateDemos = async (): Promise<{
  generated: number;
  failed: number;
}> => {
  const generated = new Set<string>();
  let failed = 0;

  for (const document of await documents()) {
    const markdown = await readFile(document, "utf-8");

    let sources: string[];

    try {
      sources = demoSources(markdown);
    } catch (error) {
      // a document half way through being written should not take the rest down
      failed++;
      console.error(
        `skipped ${path.relative(DOCS_ROOT, document)} - ${
          error instanceof Error ? error.message : error
        }`
      );

      continue;
    }

    for (const [index, source] of sources.entries()) {
      const modulePath = demoModulePath(document, index);
      if (!modulePath) continue;

      generated.add(modulePath);
      await writeModule(modulePath, `${BANNER}\n${source.trim()}\n`);
    }
  }

  /**
   * a document that could not be parsed still owns the modules it generated
   * the last time it could, so nothing is pruned until it parses again
   */
  if (!failed) await removeStaleModules(generated);

  return { generated: generated.size, failed };
};

/**
 * delete generated modules that no document claims anymore, along with any
 * folder they leave empty
 *
 * demos are numbered by their position in a document, so removing (or
 * reordering) one would otherwise leave a module behind that the remark plugin
 * happily renders for a different code block
 */
const removeStaleModules = async (generated: ReadonlySet<string>) => {
  const entries = await readdir(DEMOS_ROOT, {
    recursive: true,
    withFileTypes: true,
  }).catch(() => []);

  for (const entry of entries) {
    const entryPath = path.join(entry.parentPath, entry.name);

    if (entry.isFile() && !generated.has(entryPath)) await rm(entryPath);
  }

  // deepest first, so a folder holding nothing but empty folders goes too
  for (const entry of entries.reverse()) {
    if (!entry.isDirectory()) continue;

    const entryPath = path.join(entry.parentPath, entry.name);
    await rmdir(entryPath).catch(() => {}); // throws while it holds anything
  }
};

/** regenerate on every change under `docs/`, batching bursts of events */
const watchDocs = (onChange: () => void) => {
  let queued: NodeJS.Timeout | undefined;

  watch(DOCS_ROOT, { recursive: true }, (_event, filename) => {
    if (!filename?.endsWith(".mdx")) return;

    clearTimeout(queued);
    queued = setTimeout(onChange, 50);
  });
};

const watching = process.argv.includes("--watch");

/**
 * generate, one run at a time
 *
 * a run is queued behind the one in flight, so a burst of edits can never have
 * two of them writing (and pruning) the same modules at once
 */
let queue: Promise<void> = Promise.resolve();

const run = (): Promise<void> => {
  queue = queue.then(async () => {
    try {
      const { generated, failed } = await generateDemos();

      console.log(`generated ${generated} demo${generated === 1 ? "" : "s"}`);

      // fail `generate:demos` (and the `build` that runs it), but never `dev`
      if (failed && !watching) process.exitCode = 1;
    } catch (error) {
      console.error(error);
      if (!watching) process.exitCode = 1;
    }
  });

  return queue;
};

await run();

if (watching) {
  watchDocs(() => void run());
  console.log(`watching ${path.relative(process.cwd(), DOCS_ROOT)} for demos`);
}
